In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Data/survey_results_public.csv', index_col = 'ResponseId')
schema_df = pd.read_csv('Data/survey_results_schema.csv')

C:\Users\HomePC\AppData\Local\Temp\ipykernel_11456\3679935928.py:1: DtypeWarning: Columns (0: AIThreat, 1: DatabaseWantEntry, 2: DevEnvWantEntry, 3: SOTagsWant Entry, 4: OpSysPersonal use, 5: CommPlatformHaveWorkedWith, 6: CommPlatformWantEntr, 7: AIModelsChoice, 8: SOComm, 9: AIAgentOrchWrite, 10: AIAgentExternal) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('Data/survey_results_public.csv', index_col = 'ResponseId')

In [3]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(49191, 171)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 49191 entries, 1 to 49191
Columns: 171 entries, MainBranch to JobSat
dtypes: float64(52), str(119)
memory usage: 64.2 MB

In [6]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,...,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [7]:
df.tail()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,...,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
pd.set_option('display.max_column',150)
pd.set_option('display.max_rows', 100)

In [9]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,...,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,...,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,...,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [11]:
schema_df

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
...,...,...,...,...,...,...
134,QID103,AIAgentObsWrite,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
135,QID92,AIAgentExternal,You indicated you use or develop AI agents as ...,MC,NaN,NaN
136,QID104,AIAgentExtWrite,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
137,QID100,AIHuman,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
138,QID93,AIOpen,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN

In [12]:
df.columns

Index(['MainBranch', 'Age', 'EdLevel', 'Employment', 'EmploymentAddl',
       'WorkExp', 'LearnCodeChoose', 'LearnCode', 'LearnCodeAI', 'AILearnHow',
       ...
       'AIAgentOrchestration', 'AIAgentOrchWrite', 'AIAgentObserveSecure',
       'AIAgentObsWrite', 'AIAgentExternal', 'AIAgentExtWrite', 'AIHuman',
       'AIOpen', 'ConvertedCompYearly', 'JobSat'],
      dtype='str', length=171)

In [13]:
df.AIAgentExtWrite

ResponseId
1        NaN
2        NaN
3        NaN
4        NaN
5        NaN
        ...
49187    NaN
49188    NaN
49189    NaN
49190    NaN
49191    NaN
Name: AIAgentExtWrite, Length: 49191, dtype: str

In [14]:
df['AIAgentExternal']

ResponseId
1                                                 ChatGPT
2                                                     NaN
3        ChatGPT;Claude Code;GitHub Copilot;Google Gemini
4                                     ChatGPT;Claude Code
5                                                     NaN
                               ...
49187                                                 NaN
49188                                                 NaN
49189                                                 NaN
49190                                                 NaN
49191                                                 NaN
Name: AIAgentExternal, Length: 49191, dtype: str

In [15]:
df.loc[[2,3,4], ['AIAgentExternal', 'EmploymentAddl']]

,AIAgentExternal,EmploymentAddl
ResponseId,,
2,NaN,NaN
3,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,None of the above
4,ChatGPT;Claude Code,None of the above

In [16]:
df.iloc[[2,3], [2, 8]]

,EdLevel,LearnCodeAI
ResponseId,,
3,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Yes, I learned how to use AI-enabled tools for..."
4,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Yes, I learned how to use AI-enabled tools for..."

In [17]:
df.loc[[1, 2]]

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,...,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0

In [18]:
schema_df.columns

Index(['qid', 'qname', 'question', 'type', 'sub', 'sq_id'], dtype='str')

In [19]:
schema_df.head()

,qid,qname,question,type,sub,sq_id
0,QID18,TechEndorse_1,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
1,QID18,TechEndorse_2,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
2,QID18,TechEndorse_3,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
3,QID18,TechEndorse_4,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
4,QID18,TechEndorse_5,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0

In [20]:
schema_df.set_index('qname', inplace = True)

In [21]:
schema_df.sort_index(ascending=True, inplace = True)

In [22]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [23]:
schema_df.loc['AIAgentExtWrite', 'question']

'Was the out-of-the-box agents, copilots or assistants you used in the past year not listed above?  Please write them below separated by a comma and space if there are more than one.'

In [24]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
...,...,...,...,...,...
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [25]:
pd.set_option('display.max_rows', 139)

In [26]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [27]:
schema_df.loc['CompTotal' : 'Database']

,qid,question,type,sub,sq_id
qname,,,,,
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN

In [28]:
schema_df.loc['CompTotal', 'question']

'What is your current total <b>annual</b> compensation (salary, bonuses, and perks, before taxes and deductions) in terms of your day-to-day currency?  Please enter a whole number in the box below, without any punctuation.  If you are paid hourly, please estimate an equivalent yearly salary. If you prefer not to answer, please leave the box empty. '

In [29]:
filt = (df['CompTotal'] > 100000)

In [30]:
df.loc[filt, ['Country','MainBranch', 'Employment', 'CompTotal']]

,Country,MainBranch,Employment,CompTotal
ResponseId,,,,
3,Ukraine,I am a developer by profession,"Independent contractor, freelancer, or self-em...",2214000.0
6,Ukraine,I am a developer by profession,"Independent contractor, freelancer, or self-em...",120000.0
11,Ukraine,I am a developer by profession,Employed,2740980.0
27,Ireland,I am a developer by profession,"Independent contractor, freelancer, or self-em...",140000.0
28,Sweden,I am a developer by profession,Employed,2000000.0
...,...,...,...,...
49145,Romania,I am a developer by profession,Employed,268000.0
49146,United States of America,I am a developer by profession,"Independent contractor, freelancer, or self-em...",230000.0
49156,India,I am a developer by profession,Employed,2900000.0
49177,Kenya,I am a developer by profession,Employed,3200000.0
49180,Brazil,I am a developer by profession,Employed,180000.0

In [31]:
df['LanguageHaveWorkedWith']

ResponseId
1                         Bash/Shell (all shells);Dart;SQL
2                                                     Java
3                      Dart;HTML/CSS;JavaScript;TypeScript
4                                          Java;Kotlin;SQL
5        C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
                               ...
49187                                                  NaN
49188                                                  NaN
49189                                                  NaN
49190                                                  NaN
49191                                                  NaN
Name: LanguageHaveWorkedWith, Length: 49191, dtype: str

In [32]:
filt_lang = (df['LanguageHaveWorkedWith'].str.contains('Python', na = False))

In [33]:
df.loc[filt_lang, ['Country', 'WorkExp', 'LanguageHaveWorkedWith']]

,Country,WorkExp,LanguageHaveWorkedWith
ResponseId,,,
5,Ukraine,21.0,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...
8,Ukraine,22.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
9,Ukraine,9.0,Java;Python;Scala
16,India,5.0,Ada;Assembly;C;C#;C++;COBOL;Dart;Delphi;Elixir...
18,Greece,1.0,HTML/CSS;JavaScript;Python;SQL
...,...,...,...
49144,United Kingdom of Great Britain and Northern I...,4.0,HTML/CSS;JavaScript;Python;SQL;TypeScript
49146,United States of America,18.0,Assembly;Bash/Shell (all shells);C;C++;Python;...
49176,Germany,4.0,Bash/Shell (all shells);C#;C++;GDScript;HTML/C...
49177,Kenya,5.0,Bash/Shell (all shells);HTML/CSS;JavaScript;Py...
49178,United States of America,9.0,Bash/Shell (all shells);HTML/CSS;Lisp;PowerShe...

In [34]:
df.head()

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,ConvertedCompYearly,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,...,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,...,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,...,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0

In [35]:
df['ConvertedCompYearly']

ResponseId
1         61256.0
2        104413.0
3         53061.0
4         36197.0
5         60000.0
           ...
49187         NaN
49188         NaN
49189         NaN
49190         NaN
49191         NaN
Name: ConvertedCompYearly, Length: 49191, dtype: float64

In [36]:
schema_df
pd.set_option('display.max_rows', 139)

In [37]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [38]:
df.rename(columns = {'ConvertedCompYearly': 'SalaryUSD'}, inplace = True)

In [39]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,...,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,...,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,...,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [40]:
df['SalaryUSD']

ResponseId
1         61256.0
2        104413.0
3         53061.0
4         36197.0
5         60000.0
           ...
49187         NaN
49188         NaN
49189         NaN
49190         NaN
49191         NaN
Name: SalaryUSD, Length: 49191, dtype: float64

In [41]:
df['AIModelsChoice'].map({'Yes': 'True', 'No': 'False'})

ResponseId
1         True
2         True
3         True
4        False
5         True
         ...
49187      NaN
49188      NaN
49189      NaN
49190      NaN
49191      NaN
Name: AIModelsChoice, Length: 49191, dtype: str

In [42]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
1,I am a developer by profession,25-34 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,"Caring for dependents (children, elderly, etc.)",8.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,14.0,"Developer, mobile",20 to 99 employees,People manager,Remote,"Yes, I influenced the purchase of a substantia...",Work,10.0,7.0,9.0,6.0,3.0,11.0,12.0,1.0,8.0,14.0,NaN,15.0,7.0,8.0,12.0,11.0,1.0,6.0,13.0,3.0,16.0,NaN,Fintech,3.0,1.0,4.0,9.0,5.0,10.0,12.0,11.0,2.0,6.0,7.0,13.0,14.0,15.0,8.0,NaN,I'm not sure,I have neither consider or transitioned into a...,7.0,3.0,Ukraine,EUR European Euro,52800.0,Yes,Bash/Shell (all shells);Dart;SQL,Dart,Dart,NaN,NaN,Yes,Cloud Firestore;PostgreSQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;MacOS;Android,Windows;MacOS;Android;iOS;iPadOS,Confluence;GitHub;GitLab;Jira;Markdown File,Markdown File,Markdown File,NaN,NaN,"Stack Overflow;Reddit;GitHub (public projects,...",NaN,NaN,NaN,NaN,Yes,openAI GPT (chatbot models);openAI Image gener...,NaN,NaN,NaN,NaN,Yes,A few times per week,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,1.0,NaN,6.0,2.0,3.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools monthly or infrequently",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning about a codebase;Writing code;Search ...,Project planning;Deployment and monitoring;Lea...,Documenting code;Debugging or fixing code;Test...,NaN,NaN,"AI solutions that are almost right, but not quite",No,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,NaN,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,The cost of using certain AI agent platforms i...,NaN,NaN,NaN,NaN,Vertex AI,NaN,NaN,NaN,ChatGPT,NaN,When I don’t trust AI’s answers,"Troubleshooting, profiling, debugging",61256.0,10.0
2,I am a developer by profession,25-34 years old,"Associate degree (A.A., A.S., etc.)",Employed,NaN,2.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,"Developer, back-end",500 to 999 employees,Individual contributor,"Hybrid (some in-person, leans heavy to flexibi...",No,Personal Project,13.0,1.0,2.0,9.0,4.0,3.0,12.0,5.0,7.0,14.0,NaN,14.0,1.0,13.0,10.0,9.0,3.0,4.0,2.0,5.0,15.0,NaN,Retail and Consumer Services,10.0,8.0,3.0,9.0,12.0,1.0,6.0,2.0,11.0,4.0,7.0,13.0,14.0,15.0,5.0,NaN,I'm not sure,I have transitioned into a new career and/or i...,6.0,5.0,Netherlands,EUR European Euro,90000.0,Yes,Java,Java;Python;Swift,Java,NaN,NaN,Yes,Dynamodb;MongoDB,Dynamodb;MongoDB,Dynamodb;MongoDB,NaN,NaN,...,NaN,NaN,Windows;MacOS;iOS;iPadOS,MacOS,Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,Stack Overflow;Discord;Reddit;Dev.to;Hacker Ne...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Not sure/can't remember,Multiple times per day,Between 10 and 15 years,"Infrequently, less than once per year",Chat (people);Message Boards;Long-form article...,6.0,NaN,5.0,8.0,2.0,4.0,9.0,10.0,11.0,15.0,NaN,"Yes, somewhat",About half of the time,"Yes, I use AI tools weekly",Indifferent,Neither trust nor distrust,Bad at handling complex tasks,Learning new concepts or technologies,Learning about a codebase;Project planning;Com...,Writing code;Documenting code;Debugging or fix...,NaN,NaN,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,All skills. AI is a flop.,104413.0,9.0
3,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,12.0,"Developer, front-end",NaN,NaN,NaN,No,Work,12.0,2.0,3.0,7.0,5.0,10.0,13.0,1.0,4.0,14.0,NaN,8.0,1.0,2.0,12.0,13.0,3.0,9.0,4.0,11.0,15.0,NaN,Software Development,9.0,6.0,7.0,11.0,8.0,12.0,1.0,5.0,2.0,4.0,3.0,13.0,14.0,15.0,10.0,NaN,No,I have transitioned into a new career and/or i...,3.0,3.0,Ukraine,UAH Ukrainian hryvnia,2214000.0,Yes,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,Dart;HTML/CSS;JavaScript;TypeScript,NaN,NaN,Yes,MongoDB;MySQL;PostgreSQL,Firebase Realtime Database;MongoDB,MongoDB,NaN,NaN,...,NaN,NaN,MacOS;Android,MacOS,GitHub;GitLab;Jira,GitHub;GitLab;Jira,GitHub;GitLab;Jira,NaN,NaN,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,Stack Overflow;Discord;Dev.to;X;YouTube;LinkedIn,NaN,NaN,Yes,Gemini (Flash general purpose models);openAI G...,Gemini (Flash general purpose models);Gemini (...,Gemini (Flash general purpose models);openAI G...,NaN,NaN,Not sure/can't remember,A few times per week,Between 5 and 10 years,"Infrequently, less than once per year",Chat (people);Videos;Lists of recommendations ...,3.0,NaN,4.0,5.0,1.0,2.0,7.0,9.0,11.0,15.0,NaN,Neutral,About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,Neither good or bad at handling complex tasks,Documenting code;Debugging or fixing code;Test...,NaN,Project planning;Committing and reviewing code...,Learning about a codebase;Writing code;Generat...,NaN,"AI solutions that are almost right, but not qu...",No,"Yes, I use AI agents at work weekly","Yes, somewhat",Software engineering,Multi-platform search enablement,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,AI agents have improved collaboration within m...,NaN,NaN,It takes significant time and effort to learn ...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,NaN,Redis,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I want to...,"Understand how things actually work, problem s...",53061.0,8.0
4,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,None of the above,4.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,5.0,"Developer, back-end","10,000 or more employees",Individual contributor,Remote,No,Personal Project,2.0,12.0,6.0,5.0,13.0,3.0,8.0,11.0,7.0,14.0,NaN,10.0,5.0,8.0,4.0,13.0,12.0,2.0,7.0,1.0,15.0,NaN,Retail and Consumer Services,1.0,2.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Ukraine,EUR European Euro,31200.0,Yes,Java;Kotlin;SQL,Java;Kotlin,Java;Kotlin,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows,Windows;Ubuntu,GitLab;Jira;Miro,GitLab;Jira,GitLab;Jira,NaN,NaN,Stack Overflow;Reddit;YouTube;LinkedIn,"Stack Overflow;Reddit;GitHub (public projects,...",Stack Overflow;Reddit;YouTube;LinkedIn,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 3 and 5 years,I have never participated in Q&A on Stack Over...,Videos;Chat (bot/AI),1.0,NaN,4.0,5.0,6.0,7.0,8.0,9.0,11.0,15.0,NaN,Neutral,"Rarely, almost never","Yes, I use AI tools weekly",Favorable,Somewhat trust,Bad at handling complex tasks,NaN,Project planning;Documenting code;Testing code...,Learning about a codebase;Writing code;Debuggi...,Search for answers;Generating content or synth...,NaN,"AI solutions that are almost right, but not qu...",NO,"Yes, I use AI agents at work monthly or infreq...",Not at all or minimally,Software engineering,Language processing,AI agents have accelerated my learning about n...,AI agents have increased my productivity.;AI a...,AI agents have helped me automate repetitive t...,NaN,NaN,It takes significant time and effort to learn ...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Claude Code,NaN,When I don’t trust AI’s answers;When I want to...,NaN,36197.0,6.0
5,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",21.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,22.0,Engineering manager,NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Work,6.0,3.0,1.0,9.0,10.0,8.0,7.0,4.0,2.0,14.0,NaN,7.0,13.0,3.0,9.0,12.0,6.0,1.0,8.0,14.0,15.0,NaN,Software Development,9.0,4.0,11.0,13.0,14.0,8.0,6.0,5.0,7.0,2.0,1.0,12.0,10.0,15.0,3.0,NaN,No,I have neither consider or transitioned into a...,4.0,3.0,Ukraine,USD United States dollar,60000.0,Yes,C;C#;C++;Delphi;HTML/CSS;Java;JavaScript;Lua;P...,C#;Java;JavaScript;Python;SQL;TypeScript,C#;Java;JavaScript;Python;SQL;TypeScript,NaN,NaN,Yes,Elasticsearch;Microsoft SQL Server;MySQL;Oracl...,Elasticsearch;Oracle;PostgreSQL,Elasticsearch;Oracle;PostgreSQL,NaN,NaN,...,NaN,NaN,Windows;iOS,Windows;Ubuntu;Debian,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,Azure Devops;GitHub;Jira,NaN,NaN,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,Stack Overflow;Stack Exchange;GitHub (public p...,NaN,NaN,Yes,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,No,A few times per month or weekly,Between 5 and 10 years,"Infrequently, less than once per year",Long-form articles,1.0,NaN,7.0,4.0,2.0,5.0,10.0,6.0,12.0,15.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Project planning;Documenting code;Testing code...,Generating content or synthetic data,NaN,NaN,"AI solutions that are almost right, but not quite",partly,"No, and I don't plan to","Yes, to a great extent",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Integrating AI agents with my existing tools a...,NaN,I am concerned about the accuracy of the infor...,It takes significant time and effort to learn ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers,"critical thinking, the skill to define the tas...",60000.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,80000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
df['AIModelsChoice'] = df['AIModelsChoice'].map({'Yes': 'True', 'No': 'False'})

In [44]:
df['AIModelsChoice'].head(20)

ResponseId
1      True
2      True
3      True
4     False
5      True
6     False
7     False
8      True
9       NaN
10    False
11     True
12    False
13      NaN
14      NaN
15    False
16     True
17    False
18     True
19     True
20    False
Name: AIModelsChoice, dtype: str

In [45]:
highest_paid = df.sort_values(by='SalaryUSD', ascending=False)
highest_paid[['SalaryUSD', 'Country']]

             SalaryUSD                       Country
ResponseId
34268       50000000.0      United States of America
28701       33552715.0                       Ukraine
43144       18387548.0                        Poland
35354       15430267.0  Iran, Islamic Republic of...
45972       13921760.0                   Netherlands
...                ...                           ...
49187              NaN                           NaN
49188              NaN                           NaN
49189              NaN                         Italy
49190              NaN                           NaN
49191              NaN                           NaN

[49191 rows x 2 columns]

In [46]:
highest_paid

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,10.0,"Developer, embedded applications or devices",NaN,NaN,NaN,NaN,Personal Project,5.0,7.0,8.0,4.0,3.0,9.0,6.0,1.0,2.0,10.0,NaN,4.0,8.0,2.0,7.0,1.0,3.0,5.0,6.0,9.0,10.0,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,10.0,United States of America,USD United States dollar,5.000000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,Learning about a codebase;Project planning;Wri...,Predictive analytics,Learning new concepts or technologies,Other (write in):,N0,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,27.0,"Developer, full-stack",100 to 499 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,4.0,2.0,3.0,6.0,7.0,1.0,8.0,5.0,9.0,10.0,NaN,7.0,5.0,6.0,8.0,9.0,2.0,4.0,3.0,1.0,10.0,NaN,Software Development,10.0,11.0,7.0,13.0,4.0,12.0,2.0,8.0,9.0,3.0,1.0,5.0,6.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,10.0,3.0,Ukraine,UAH Ukrainian hryvnia,1.400000e+09,Yes,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,NaN,NaN,Yes,Cosmos DB;Dynamodb;Microsoft SQL Server;Postgr...,Cosmos DB;Dynamodb;Microsoft SQL Server,Cosmos DB;Dynamodb;Microsoft SQL Server,NaN,NaN,...,NaN,NaN,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium;Company...,Stack Overflow;Medium;Company-sponsored forums,Stack Overflow;Medium;Company-sponsored forums,NaN,NaN,True,openAI Reasoning models;Perplexity Sonar models,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Chat (people);Coding challenges;Chat (bot/AI),3.0,9.0,7.0,6.0,4.0,1.0,8.0,5.0,2.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,NaN,Deployment and monitoring,NaN,"AI solutions that are almost right, but not qu...",Yes,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Decision intelligence;Dat...,Language processing;MCP servers,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,Integrating AI agents with my existing tools a...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,Financial analyst or engineer,100 to 499 employees,NaN,"Hybrid (some remote, leans heavy to in-person)",No,Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,5.0,1.0,Poland,BRL Brazilian real,1.010101e+08,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;Android,Windows,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,NaN,I have never participated in Q&A on Stack Over...,Logic games/puzzles,9.0,2.0,7.0,6.0,4.0,3.0,1.0,5.0,8.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Favorable,NaN,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,Other (write in):,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,12.0,Engineering manager,100 to 499 employees,People manager,"Hybrid (some remote, leans heavy to in-person)",No,Work,7.0,6.0,2.0,4.0,8.0,9.0,3.0,5.0,1.0,10.0,NaN,4.0,6.0,7.0,1.0,3.0,8.0,2.0,9.0,5.0,10.0,NaN,Computer Systems Design and Services,11.0,7.0,14.0,5.0,12.0,1.0,2.0,4.0,3.0,6.0,8.0,13.0,9.0,15.0,10.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,"Iran, Islamic Republic of...",IRR\tIranian rial,6.500000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,I have never participated in Q&A on Stack Over...,Long-form articles;Lists of recommendations (t...,8.0,5.0,7.0,4.0,3.0,2.0,1.0,9.0,6.0,10.0,NaN,Neutral,"Rarely, almost never","No, and I don't plan to",Unsure,Highly distrust,Neither good or bad at handling complex tasks,Other (write in):,NaN,Committing and reviewing code;Predictive analy...,Project planning;Writing code;Debugging or fix...,Learning about a codebase;Generating content o...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;IT operations;Customer se...,Integration with external agents and APIs,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,10.0,"Senior executive (C-suite, VP, etc.)","1,000 to 4,999 employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,2.0,5.0,8.0,3.0,1.0,9.0,6.0,7.0,4.0,10.0,NaN,8.0,6.0,4.0,1.0,5.0,2.0,3.0,7.0,9.0,10.0,NaN,"Internet, Telecomm or Information Services",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Netherlands,EUR European Euro,1.200000e+07,NaN,Java;Kotlin,Go;Java;Rust,Java,NaN,NaN,Yes,Supabase;Clickhouse,Supabase;Clickhouse,Supabase;Clickhouse,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,Gemini (Flash general purpose models),Gemini (Flash general purpose models),Gemini (Flash general purpose models),NaN,NaN,No,"Infrequently, less than once per year",Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49189,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,None of the above,17.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Videos (no...,31.0,"Architect, software or solutions","10,000 or more employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I endorsed a tool that was open-source an...",Personal Project,9.0,2.0,1.0,5.0,3.0,7.0,8.0,4.0,6.0,10.0,NaN,9.0,6.0,2.0,7.0,5.0,4.0,1.0,3.0,8.0,10.0,NaN,Banking/Financial Services,3.0,6.0,7.0,13.0,4.0,9.0,1.0,10.0,2.0,5.0,8.0,11.0,12.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,25.0,35.0,Italy,EUR European Euro,8.000000e+04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools monthly or infrequently",Favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Documen...,Debugging or fixing code,Project planning;Deployment and monitoring;Pre...,NaN,Search for answers,"AI solutions that are almost right, but not qu...","Yes, partially.","No, I use AI exclusively in copilot/autocomple...",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9.0
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [47]:
df.sort_values(by=['SalaryUSD','Country'], ascending=[False,True], inplace=True)

In [48]:
df[['SalaryUSD', 'Country']].head(8)

             SalaryUSD                       Country
ResponseId
34268       50000000.0      United States of America
28701       33552715.0                       Ukraine
43144       18387548.0                        Poland
35354       15430267.0  Iran, Islamic Republic of...
45972       13921760.0                   Netherlands
48429       10000000.0                       Ukraine
24901        9531653.0                         India
10026        9000000.0      United States of America

In [49]:
df['Country'].sort_values().head(26)

ResponseId
7925     Afghanistan
38609    Afghanistan
6010     Afghanistan
7167     Afghanistan
40967    Afghanistan
44797    Afghanistan
27099    Afghanistan
45925    Afghanistan
40307    Afghanistan
19816    Afghanistan
15708    Afghanistan
6836     Afghanistan
7077     Afghanistan
11874        Albania
16850        Albania
2023         Albania
33940        Albania
37731        Albania
3185         Albania
22400        Albania
14758        Albania
35934        Albania
16239        Albania
44946        Albania
25304        Albania
35184        Albania
Name: Country, dtype: str

In [50]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,10.0,"Developer, embedded applications or devices",NaN,NaN,NaN,NaN,Personal Project,5.0,7.0,8.0,4.0,3.0,9.0,6.0,1.0,2.0,10.0,NaN,4.0,8.0,2.0,7.0,1.0,3.0,5.0,6.0,9.0,10.0,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,10.0,United States of America,USD United States dollar,5.000000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,Learning about a codebase;Project planning;Wri...,Predictive analytics,Learning new concepts or technologies,Other (write in):,N0,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,27.0,"Developer, full-stack",100 to 499 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,4.0,2.0,3.0,6.0,7.0,1.0,8.0,5.0,9.0,10.0,NaN,7.0,5.0,6.0,8.0,9.0,2.0,4.0,3.0,1.0,10.0,NaN,Software Development,10.0,11.0,7.0,13.0,4.0,12.0,2.0,8.0,9.0,3.0,1.0,5.0,6.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,10.0,3.0,Ukraine,UAH Ukrainian hryvnia,1.400000e+09,Yes,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,NaN,NaN,Yes,Cosmos DB;Dynamodb;Microsoft SQL Server;Postgr...,Cosmos DB;Dynamodb;Microsoft SQL Server,Cosmos DB;Dynamodb;Microsoft SQL Server,NaN,NaN,...,NaN,NaN,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium;Company...,Stack Overflow;Medium;Company-sponsored forums,Stack Overflow;Medium;Company-sponsored forums,NaN,NaN,True,openAI Reasoning models;Perplexity Sonar models,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Chat (people);Coding challenges;Chat (bot/AI),3.0,9.0,7.0,6.0,4.0,1.0,8.0,5.0,2.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,NaN,Deployment and monitoring,NaN,"AI solutions that are almost right, but not qu...",Yes,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Decision intelligence;Dat...,Language processing;MCP servers,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,Integrating AI agents with my existing tools a...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,Financial analyst or engineer,100 to 499 employees,NaN,"Hybrid (some remote, leans heavy to in-person)",No,Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,5.0,1.0,Poland,BRL Brazilian real,1.010101e+08,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;Android,Windows,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,NaN,I have never participated in Q&A on Stack Over...,Logic games/puzzles,9.0,2.0,7.0,6.0,4.0,3.0,1.0,5.0,8.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Favorable,NaN,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,Other (write in):,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,12.0,Engineering manager,100 to 499 employees,People manager,"Hybrid (some remote, leans heavy to in-person)",No,Work,7.0,6.0,2.0,4.0,8.0,9.0,3.0,5.0,1.0,10.0,NaN,4.0,6.0,7.0,1.0,3.0,8.0,2.0,9.0,5.0,10.0,NaN,Computer Systems Design and Services,11.0,7.0,14.0,5.0,12.0,1.0,2.0,4.0,3.0,6.0,8.0,13.0,9.0,15.0,10.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,"Iran, Islamic Republic of...",IRR\tIranian rial,6.500000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,I have never participated in Q&A on Stack Over...,Long-form articles;Lists of recommendations (t...,8.0,5.0,7.0,4.0,3.0,2.0,1.0,9.0,6.0,10.0,NaN,Neutral,"Rarely, almost never","No, and I don't plan to",Unsure,Highly distrust,Neither good or bad at handling complex tasks,Other (write in):,NaN,Committing and reviewing code;Predictive analy...,Project planning;Writing code;Debugging or fix...,Learning about a codebase;Generating content o...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;IT operations;Customer se...,Integration with external agents and APIs,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,10.0,"Senior executive (C-suite, VP, etc.)","1,000 to 4,999 employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,2.0,5.0,8.0,3.0,1.0,9.0,6.0,7.0,4.0,10.0,NaN,8.0,6.0,4.0,1.0,5.0,2.0,3.0,7.0,9.0,10.0,NaN,"Internet, Telecomm or Information Services",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Netherlands,EUR European Euro,1.200000e+07,NaN,Java;Kotlin,Go;Java;Rust,Java,NaN,NaN,Yes,Supabase;Clickhouse,Supabase;Clickhouse,Supabase;Clickhouse,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,Gemini (Flash general purpose models),Gemini (Flash general purpose models),Gemini (Flash general purpose models),NaN,NaN,No,"Infrequently, less than once per year",Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [51]:
df[['SalaryUSD', 'Employment']].head(8)

             SalaryUSD                                         Employment
ResponseId
34268       50000000.0  Independent contractor, freelancer, or self-em...
28701       33552715.0                                           Employed
43144       18387548.0                                           Employed
35354       15430267.0                                           Employed
45972       13921760.0                                           Employed
48429       10000000.0                                            Student
24901        9531653.0                                           Employed
10026        9000000.0                                           Employed

In [52]:
df['SalaryUSD'].nlargest(15)

ResponseId
34268    50000000.0
28701    33552715.0
43144    18387548.0
35354    15430267.0
45972    13921760.0
48429    10000000.0
24901     9531653.0
10026     9000000.0
37353     6890299.0
30729     6371285.0
40419     6000000.0
19537     5810837.0
28056     5000000.0
14874     4706124.0
48024     3900562.0
Name: SalaryUSD, dtype: float64

In [53]:
df['SalaryUSD'].nsmallest(15)

ResponseId
34866    1.0
41683    1.0
34568    1.0
27893    1.0
28178    1.0
42079    1.0
4581     1.0
16490    1.0
91       1.0
5911     1.0
13305    1.0
21035    1.0
26962    1.0
12408    1.0
39052    1.0
Name: SalaryUSD, dtype: float64

In [54]:
df.nsmallest(5, 'SalaryUSD')

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34866,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (less than 10 hours per w...,16.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps;Technical ...,20.0,"Developer, full-stack",20 to 99 employees,Individual contributor,Remote,"Yes, I influenced the purchase of a substantia...",Work,8.0,2.0,1.0,7.0,4.0,9.0,5.0,6.0,3.0,10.0,NaN,9.0,2.0,8.0,5.0,1.0,6.0,3.0,4.0,7.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have somewhat considered changing my career ...,10.0,4.0,Antigua and Barbuda,LYD Libyan dinar,5.0,Yes,Bash/Shell (all shells);C;Go;HTML/CSS;JavaScri...,NaN,NaN,NaN,NaN,Yes,MariaDB;PostgreSQL;SQLite;Supabase,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;Arch,Windows;Arch,GitHub;GitLab;Markdown File;Obsidian;YouTrack,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,Alibaba Cloud Qwen models;Anthropic: Claude So...,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 10 and 15 years,"Infrequently, less than once per year",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Favorable,Highly distrust,Very poor at handling complex tasks,Project planning;Writing code;Search for answe...,Learning about a codebase;Debugging or fixing ...,Documenting code,Generating content or synthetic data,NaN,"AI solutions that are almost right, but not qu...","It is mostly ""frustration coding"" then ""vibe c...","Yes, I use AI agents at work weekly",Not at all or minimally,Software engineering,NaN,AI agents have reduced the time spent on speci...,AI agents have increased my productivity.;AI a...,AI agents have accelerated my learning about n...,NaN,AI agents have improved the quality of my code...,My company's IT and/or InfoSec teams have stri...,NaN,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,supabase;Milvus,NaN,Ollama,NaN,NaN,NaN,ChatGPT;Claude Code;GitHub Copilot;Google Gemi...,NaN,When I don’t trust AI’s answers;When I want to...,all of them,1.0,8.0
41683,"I am not primarily a developer, but I write co...",45-54 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)","Independent contractor, freelancer, or self-em...",None of the above,13.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","No, I learned something that was not related t...",NaN,13.0,"Developer, desktop or enterprise applications",NaN,NaN,NaN,No,Personal Project,9.0,1.0,3.0,2.0,6.0,4.0,5.0,7.0,8.0,10.0,NaN,5.0,9.0,7.0,3.0,4.0,8.0,2.0,6.0,1.0,10.0,NaN,Software Development,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,1.0,1.0,Bulgaria,BGN\tBulgarian lev,1.0,Yes,C#;C++;Python;SQL,NaN,NaN,maxscript,NaN,Yes,Microsoft SQL Server;MySQL,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows,NaN,GitHub,NaN,NaN,NaN,NaN,"Stack Overflow;GitHub (public projects, not pr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 1 and 3 years,"Infrequently, less than once per year",Message Boards;Long-form articles;Videos;Logic...,9.0,3.0,5.0,6.0,1.0,2.0,4.0,7.0,8.0,10.0,NaN,"No, not at all",About half of the time,"Yes, I use AI tools daily",Favorable,Somewhat trust,"Good, but not great at handling complex tasks",NaN,NaN,NaN,NaN,Testing code,"AI solutions that are almost right, but not quite",NaN,"No, and I don't plan to","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to fully understand something,AI provides the code but if it is not somethin...,1.0,NaN
34568,I am a developer by profession,25-34 years old,Primary/elementary school,Employed,Volunteering (regularly),8.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,10.0,AI/ML engineer,"10,000 or more employees",Individual contributor,"Hybrid (some remote, leans heavy to in-person)","Yes, I influenced the purchase of a substantia...",Work,7.0,8.0,3.0,1.0,5.0,4.0,9.0,2.0,6.0,10.0,NaN,9.0,7.0,1.0,3.0,6.0,4.0,2.0,8.0,5.0,10.0,NaN,Software Development,14.0,9.0,8.0,11.0,4.0,3.0,2.0,6.0,7.0,13.0,12.0,1.0,5.0,15.0,10.0,NaN,No,I have strongly considered changing my career ...,3.0,3.0,China,CNY\tChinese Yuan Renminbi,5.0,Yes,C;C++;Java;MATLAB;Python,NaN,NaN,java,python,Yes,MySQL;Neo4J;Oracle,NaN,NaN,mysql,mysql,...,RAG,RAG,Windows;Ubuntu;Linux (non-WSL),NaN,Coda;GitHub;GitLab;Google Colab,NaN,NaN,CODA,CODA,Stack Overflow,NaN,NaN,x,x,NaN,Alibaba Cloud Qwen models,NaN,NaN,qwen,qwen,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,NaN,NaN,Committing and reviewing code;Creating or main...,I’ve become less confident in my own problem-s...,"n my professional development work, ""vibe codi...","Yes, I use AI agents at work daily","Yes, to a great extent",Business process automation,Agent/multi-agent orchestration,NaN,NaN,NaN,AI agents have increased my productivity.,NaN,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,5.0
27893,I am learning to code,35-44 years old,Some college/university study without earning ...,Not employed,None of the above,12.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"No, I learned something that was not related t...",NaN,6.0,Student,NaN,NaN,NaN,NaN,Personal Project,7.0,6.0,9.0,5.0,1.0,3.0,8.0,4.0,2.0,10.0,NaN,8.0,4.0,7.0,2.0,1.0,6.0,9.0,3.0,5.0,10.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have strongly considered changing my career ...,4.0,5.0,Colombia,COP\tColombian peso,4000.0,Yes,HTML/CSS;Java,HTML/CSS;JavaScript;TypeScript,HTML/CSS,NaN,NaN,Yes,MariaDB;MongoDB;MySQL,MongoDB,MongoDB,NaN,NaN,...,NaN,NaN,Windows,Windows;Ubuntu,GitHub;GitLab,GitHub,GitHub,NaN,NaN,Stack Overflow;Discord,Stack Overflow;Discord,Stack Overflow;Discord,NaN,NaN,False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools weekly",Favorable,Neither trust nor distrust,NaN,NaN,NaN,NaN,NaN,NaN,I haven’t encountered any problems,NaN,"No, but I plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN
28178,I am a developer by profession,18-24 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",Volunteering (regularly);Engaged in paid work ...,1.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",Videos (not associated with specific online co...,4.0,"Developer, AI apps or physical AI","Just me - I am a freelancer, sole proprietor, ...",Individual contributor,"Your choice (very flexible, you can come in wh...","Yes, I influenced the purchase of a tool that ...",Work,7.0,6.0,1.0,5.0,4.0,8.0,9.0,3.0,2.0,10.0,NaN,5.0,3.0,4.0,7.0,9.0,1.0,2.0,6.0,8.0,10.0,NaN,Software Development,4.0,7.0,5.0,3.0,6.0,10.0,9.0,13.0,12.0,11.0,2.0,1.0,8.0,15.0,14.0,NaN,Yes,I have somewhat considered changing my career ...,4.0,4.0,Colombia,COP\tColombian peso,5800.0,Yes,Bash/Shell (all shells);HTML/CSS;Java;Python;S...,Bash/Shell (all shells);HTML/CSS;Java;Kotlin;L...,Bash/Shell (all shells);HTML/CSS;Java;Python;S...,NaN,NaN,Yes,Microsoft SQL Server;MongoDB;PostgreSQL,BigQuery;Microsoft SQL Server;MongoDB;MySQL;Po...,Microsoft SQL Server;MongoDB;PostgreSQL,NaN,NaN,...,NaN,NaN,Android;Arch,Debian;Arch,Azure Devops;GitHub;Markdown File,GitHub;Jira;Markdown File;Wikis,GitHub;Markdown File,NaN,NaN,"GitHub (public projects, not private repos);Yo...","Discord;GitHub (public projects, not private r...","GitHub (public projects, not private repos);Yo...",NaN,NaN,True,DeepSeek (R- Reasoning models);Gemini (Pro Rea...,Gemini (Pro Reasoning models);openAI GPT (chat...,Gemini (Pro Reasoning models);openAI GPT (chat...,NaN,NaN,Yes,Less than once per month or monthly,I don't use Stack Overflow,I have never participated in Q&A on Stack Over...,NaN,4.0,5.0,3.0,6.0,2.0,8.0,9.0,1.0,7.0,10.0,NaN,"No, not at all",Less than half of the time,"Yes, I use AI tools daily",Favorable,Neither trust nor distrust,Neither good or bad at handling complex tasks,Writing code;Deployment and monitoring;Search ...,Learning about a codebase;Debugging or fixing ...,NaN,Project planning,Documenting code;Creating or maintaining docum...,"AI solutions that are almost right, but not qu...",No,"No, and I don't plan to","No, but my development work has changed somewh...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,My company's IT and/or InfoSec teams have stri...,I am concerned about the accuracy of the infor...,The cost of using certain AI agent platforms i...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,Solve any problem with logic,1.0,8.0

In [55]:
df['SalaryUSD'].median()

np.float64(75320.0)

In [56]:
float(np.float64(75320.0))

75320.0

In [57]:
float(df['SalaryUSD'].mean())

101761.53990061386

In [58]:
df['SalaryUSD'].describe()

count    2.394700e+04
mean     1.017615e+05
std      4.617569e+05
min      1.000000e+00
25%      3.817100e+04
50%      7.532000e+04
75%      1.205960e+05
max      5.000000e+07
Name: SalaryUSD, dtype: float64

In [59]:
df.describe()

,WorkExp,YearsCode,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,ToolCountWork,ToolCountPersonal,CompTotal,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SalaryUSD,JobSat
count,42893.000000,43042.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,35975.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,34259.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,24943.000000,27611.000000,25582.000000,2.486600e+04,26260.000000,24340.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,26260.000000,2.394700e+04,26670.000000
mean,13.367403,16.570861,7.867352,4.104211,4.110271,5.678193,4.119388,5.225990,6.477387,4.370841,4.431661,9.854315,8.307948,4.524067,5.925567,4.991710,4.048980,3.799323,4.365831,5.059867,5.508538,9.945766,6.867738,5.216173,7.455719,9.537947,9.758209,8.194965,5.884096,7.367799,6.744658,7.512569,5.703283,8.563324,8.679349,14.687487,7.826685,17.734852,8.545579,2.234198e+70,4.907845,3.339770,5.718355,4.561767,4.790861,5.199657,5.676314,4.984653,7.099505,10.079284,1.017615e+05,7.201950
std,10.800117,11.787610,2.397432,2.275821,2.329536,2.398084,2.437945,2.801045,2.331468,2.357058,2.620901,1.975692,2.202164,2.282867,2.301937,2.294707,2.607443,2.499468,2.557152,2.533541,2.906146,2.087463,3.741490,3.660632,3.726759,3.781286,3.557588,3.801257,3.900813,4.118532,3.888845,3.847265,4.110528,3.545288,3.633175,1.898188,4.077460,269.810134,44.664738,3.523096e+72,2.682204,2.411404,2.628016,3.070548,2.643177,2.563562,2.310659,2.490095,2.469394,1.940928,4.617569e+05,1.997245
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000e+00,0.000000
25%,5.000000,8.000000,7.000000,2.000000,2.000000,4.000000,2.000000,3.000000,5.000000,2.000000,2.000000,10.000000,8.000000,3.000000,4.000000,3.000000,2.000000,2.000000,2.000000,3.000000,3.000000,10.000000,4.000000,2.000000,4.000000,7.000000,7.000000,5.000000,2.000000,4.000000,3.000000,4.000000,2.000000,6.000000,6.000000,15.000000,4.000000,4.000000,3.000000,5.500000e+04,3.000000,1.000000,3.000000,1.000000,3.000000,3.000000,4.000000,3.000000,6.000000,10.000000,3.817100e+04,6.000000
50%,10.000000,14.000000,9.000000,4.000000,4.000000,6.000000,4.000000,5.000000,7.000000,4.000000,4.000000,10.000000,9.000000,4.000000,6.000000,5.000000,4.000000,3.000000,4.000000,5.000000,6.000000,10.000000,6.000000,4.000000,7.000000,10.000000,10.000000,8.000000,5.000000,7.000000,6.000000,7.000000,5.000000,9.000000,9.000000,15.000000,8.000000,6.000000,5.000000,1.050000e+05,5.000000,2.000000,6.000000,4.000000,5.000000,5.000000,6.000000,5.000000,8.000000,10.000000,7.532000e+04,8.000000
75%,20.000000,24.000000,9.000000,6.000000,6.000000,8.000000,6.000000,8.000000,8.000000,6.000000,7.000000,10.000000,9.000000,6.000000,8.000000,7.000000,6.000000,6.000000,6.000000,7.000000,8.000000,10.000000,10.000000,8.000000,11.000000,13.000000,13.000000,11.000000,9.000000,11.000000,10.000000,11.000000,9.000000,12.000000,12.000000,15.000000,11.000000,10.000000,7.000000,2.400000e+05,7.000000,5.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,9.000000,10.000000,1.205960e+05,8.000000
max,100.000000,100.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,14.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,14.000000,15.000000,15.000000,16.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,10000.000000,1000.000000,5.555556e+74,15.000000,10.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,15.000000,5.000000e+07,10.000000

In [60]:
df['SalaryUSD'].count()
float(df['SalaryUSD'].count())

23947.0

In [61]:
df

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
34268,I code primarily as a hobby,55-64 years old,"Associate degree (A.A., A.S., etc.)","Independent contractor, freelancer, or self-em...",None of the above,10.0,"Yes, I am not new to coding but am learning ne...","Other online resources (e.g. standard search, ...","Yes, I learned how to use AI-enabled tools for...",Technical documentation (is generated for/by t...,10.0,"Developer, embedded applications or devices",NaN,NaN,NaN,NaN,Personal Project,5.0,7.0,8.0,4.0,3.0,9.0,6.0,1.0,2.0,10.0,NaN,4.0,8.0,2.0,7.0,1.0,3.0,5.0,6.0,9.0,10.0,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,10.0,United States of America,USD United States dollar,5.000000e+07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"Yes, I use AI tools daily",Very favorable,Highly trust,Very well at handling complex tasks,NaN,NaN,Learning about a codebase;Project planning;Wri...,Predictive analytics,Learning new concepts or technologies,Other (write in):,N0,"No, and I don't plan to","No, but my development work has significantly ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000000.0,NaN
28701,I am a developer by profession,35-44 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",AI CodeGen tools or AI-enabled apps,27.0,"Developer, full-stack",100 to 499 employees,People manager,Remote,"Yes, I influenced the purchase of a tool that ...",Work,4.0,2.0,3.0,6.0,7.0,1.0,8.0,5.0,9.0,10.0,NaN,7.0,5.0,6.0,8.0,9.0,2.0,4.0,3.0,1.0,10.0,NaN,Software Development,10.0,11.0,7.0,13.0,4.0,12.0,2.0,8.0,9.0,3.0,1.0,5.0,6.0,15.0,14.0,NaN,No,I have somewhat considered changing my career ...,10.0,3.0,Ukraine,UAH Ukrainian hryvnia,1.400000e+09,Yes,C#;HTML/CSS;JavaScript;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,C#;HTML/CSS;SQL;TypeScript,NaN,NaN,Yes,Cosmos DB;Dynamodb;Microsoft SQL Server;Postgr...,Cosmos DB;Dynamodb;Microsoft SQL Server,Cosmos DB;Dynamodb;Microsoft SQL Server,NaN,NaN,...,NaN,NaN,Windows;Windows Subsystem for Linux (WSL),Windows;Windows Subsystem for Linux (WSL),Confluence;GitHub;Jira,Confluence;GitHub;Jira,Confluence;GitHub;Jira,NaN,NaN,Stack Overflow;YouTube;LinkedIn;Medium;Company...,Stack Overflow;Medium;Company-sponsored forums,Stack Overflow;Medium;Company-sponsored forums,NaN,NaN,True,openAI Reasoning models;Perplexity Sonar models,NaN,NaN,NaN,NaN,Yes,A few times per month or weekly,Between 5 and 10 years,I have never participated in Q&A on Stack Over...,Chat (people);Coding challenges;Chat (bot/AI),3.0,9.0,7.0,6.0,4.0,1.0,8.0,5.0,2.0,10.0,NaN,"No, not really","Rarely, almost never","Yes, I use AI tools daily",Very favorable,Somewhat trust,Neither good or bad at handling complex tasks,Learning about a codebase;Project planning;Wri...,NaN,NaN,Deployment and monitoring,NaN,"AI solutions that are almost right, but not qu...",Yes,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;Decision intelligence;Dat...,Language processing;MCP servers,NaN,AI agents have improved collaboration within m...,NaN,AI agents have increased my productivity.;AI a...,NaN,Integrating AI agents with my existing tools a...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;GitHub Copilot;Google Gemini,NaN,When I don’t trust AI’s answers;When I have et...,NaN,33552715.0,7.0
43144,I code primarily as a hobby,18-24 years old,"Associate degree (A.A., A.S., etc.)",Employed,Engaged in paid work (20-29 hours per week);En...,10.0,"Yes, I am not new to coding but am learning ne...",Other (please specify):,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,10.0,Financial analyst or engineer,100 to 499 employees,NaN,"Hybrid (some remote, leans heavy to in-person)",No,Work,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Other:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,I have neither consider or transitioned into a...,5.0,1.0,Poland,BRL Brazilian real,1.010101e+08,No,NaN,NaN,NaN,NaN,NaN,No,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,Windows;Android,Windows,NaN,NaN,NaN,NaN,NaN,Stack Overflow;Stack Exchange,NaN,NaN,NaN,NaN,NaN,openAI GPT (chatbot models),openAI GPT (chatbot models),openAI GPT (chatbot models),NaN,NaN,Yes,A few times per month or weekly,NaN,I have never participated in Q&A on Stack Over...,Logic games/puzzles,9.0,2.0,7.0,6.0,4.0,3.0,1.0,5.0,8.0,10.0,NaN,"Yes, somewhat","Rarely, almost never","No, and I don't plan to",Favorable,NaN,I don't use AI tools for complex tasks / I don...,NaN,NaN,NaN,NaN,NaN,Other (write in):,NaN,"No, and I don't plan to",Not at all or minimally,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,being laid off,18387548.0,NaN
35354,I am a developer by profession,35-44 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,Engaged in paid work (20-29 hours per week),15.0,"No, I am not new to coding and did not learn n...",NaN,NaN,NaN,12.0,Engineering manager,100 to 499 employees,People manager,"Hybrid (some remote, leans heavy to in-person)",No,Work,7.0,6.0,2.0,4.0,8.0,9.0,3.0,5.0,1.0,10.0,NaN,4.0,6.0,7.0,1.0,3.0,8.0,2.0,9.0,5.0,10.0,NaN,Computer Systems Design and Services,11.0,7.0,14.0,5.0,12.0,1.0,2.0,4.0,3.0,6.0,8.0,13.0,9.0,15.0,10.0,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,"Iran, Islamic Republic of...",IRR\tIranian rial,6.500000e+11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Yes,Less than once per month or monthly,Less than one year,I have never participated in Q&A on Stack Over...,Long-form articles;Lists of recommendations (t...,8.0,5.0,7.0,4.0,3.0,2.0,1.0,9.0,6.0,10.0,NaN,Neutral,"Rarely, almost never","No, and I don't plan to",Unsure,Highly distrust,Neither good or bad at handling complex tasks,Other (write in):,NaN,Committing and reviewing code;Predictive analy...,Project planning;Writing code;Debugging or fix...,Learning about a codebase;Generating content o...,"AI solutions that are almost right, but not qu...",NaN,"Yes, I use AI agents at work daily","Yes, somewhat",Software engineering;IT operations;Customer se...,Integration with external agents and APIs,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved the quality of my code...,NaN,NaN,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ChatGPT;Google Gemini,NaN,When I’m stuck and can’t explain the problem,NaN,15430267.0,8.0
45972,I work with developers or my work supports dev...,55-64 years old,"Master’s degree (M.A., M.S., M.Eng., MBA, etc.)",Employed,Engaged in paid work (20-29 hours per week),30.0,"Yes, I am not new to coding but am learning ne...",Colleague or on-the-job training,"Yes, I learned how to use AI-enabled tools req...",Colleague or on-the-job training,10.0,"Senior executive (C-suite, VP, etc.)","1,000 to 4,999 employees",People manager,"Hybrid (some in-person, leans heavy to flexibi...","Yes, I influenced the purchase of a substantia...",Work,2.0,5.0,8.0,3.0,1.0,9.0,6.0,7.0,4.0,10.0,NaN,8.0,6.0,4.0,1.0,5.0,2.0,3.0,7.0,9.0,10.0,NaN,"Internet, Telecomm or Information Services",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,No,I have neither consider or transitioned into a...,NaN,NaN,Netherlands,EUR European Euro,1.200000e+07,NaN,Java;Kotlin,Go;Java;Rust,Java,NaN,NaN,Yes,Supabase;Clickhouse,Supabase;Clickhouse,Supabase;Clickhouse,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,True,Gemini (Flash general purpose models),Gemini (Flash general purpose models),Gemini (Flash general purpose models),NaN,NaN,No,"Infrequently, less than once per year",Between 5 and 10 years,I have never participated in Q&A on Stack Over...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,13921760.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49186,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49187,I code primarily as a hobby,18-24 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)",Employed,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49188,I am a developer by profession,45-54 years old,Some college/university study without earning ...,Employed,"Caring for dependents (children, elderly, etc.)",25.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49190,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...",None of the above,2.0,"Yes, I am not new to coding but am learning ne...",Videos (not associated with specific online co...,"Yes, I learned how to use AI-enabled tools for...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49191,"I am not primarily a developer, but I write co...",18-24 years old,Some college/university study without earning ...,Student,Attending school (full-time),NaN,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools for...",AI CodeGen tools or AI-enabled apps,6.0,Student,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [62]:
df['AIExplain'].value_counts()

AIExplain
No                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     6716
no                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     3400
No.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    1121
Yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     763
yes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     571
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       ...
Depends, it can be when I have to use unfamiliar technologies for tasks that have strict deadlines and little time to understand enough, like building ML models                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          1
no, i don't think so                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      1
import 'package:flutter/material.dart';\n\nvoid main() { runApp(const CustomJeansApp()); }\n\nclass CustomJeansApp extends StatelessWidget { const CustomJeansApp({super.key});\n\n@override Widget build(BuildContext context) { return MaterialApp( title: 'Custom Jeans App', theme: ThemeData( primarySwatch: Colors.indigo, visualDensity: VisualDensity.adaptivePlatformDensity, ), home: const LoginScreen(), ); } }\n\nclass LoginScreen extends StatelessWidget { const LoginScreen({super.key});\n\n@override Widget build(BuildContext context) { return Scaffold( backgroundColor: Colors.white, body: Padding( padding: const EdgeInsets.all(24.0), child: Column( mainAxisAlignment: MainAxisAlignment.center, children: [ const Text( 'Welcome to JAE THEE DESIGNER', style: TextStyle(fontSize: 24, fontWeight: FontWeight.bold), textAlign: TextAlign.center, ), const SizedBox(height: 32), TextField( decoration: InputDecoration( labelText: 'Email', border: OutlineInputBorder(), ), ), const SizedBox(height: 16), TextField( obscureText: true, decoration: InputDecoration( labelText: 'Password', border: OutlineInputBorder(), ), ), const SizedBox(height: 24), ElevatedButton( onPressed: () { Navigator.push( context, MaterialPageRoute(builder: (context) => const HomeScreen()), ); }, child: const Text('Login'), ), ], ), ), ); } }\n\nclass HomeScreen extends StatelessWidget { const HomeScreen({super.key});\n\n@override Widget build(BuildContext context) { return Scaffold( appBar: AppBar(title: const Text('Home')), body: Center( child: ElevatedButton( onPressed: () { Navigator.push( context, MaterialPageRoute(builder: (context) => const DesignScreen()), ); }, child: const Text('Design Your Jeans'), ), ), ); } }\n\nclass DesignScreen extends StatelessWidget { const DesignScreen({super.key});\n\n@override Widget build(BuildContext context) { return Scaffold( appBar: AppBar(title: const Text('Custom Jeans Designer')), body: Padding( padding: const EdgeInsets.all(16.0), child: Column( children: const [ Text('Choose Your Options:', style: TextStyle(fontSize: 18)), SizedBox(height: 16), Text('• Fit: Skinny, Straight, Relaxed'), Text('• Fabric: Light, Medium, Heavy Denim'), Text('• Color: Blue,\n\n       1

In [63]:
schema_df

,qid,question,type,sub,sq_id
qname,,,,,
AIAcc,QID80,How much do you trust the accuracy of the outp...,MC,NaN,NaN
AIAgentChallenges,QID88,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentChange,QID83,Have AI tools or AI agents changed how you com...,MC,NaN,NaN
AIAgentExtWrite,QID104,"Was the out-of-the-box agents, copilots or ass...",TE,NaN,NaN
AIAgentExternal,QID92,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentImpact,QID87,To what extent do you agree with the following...,Matrix,NaN,NaN
AIAgentKnowWrite,QID107,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentKnowledge,QID89,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentObsWrite,QID103,Was the tool or tools for AI agent observabili...,TE,NaN,NaN
AIAgentObserveSecure,QID91,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgentOrchWrite,QID102,Was the tool or tools for AI agent orchestrati...,TE,NaN,NaN
AIAgentOrchestration,QID90,You indicated you use or develop AI agents as ...,MC,NaN,NaN
AIAgent_Uses,QID86,What industry purposes or specific tasks are y...,MC,NaN,NaN
AIAgents,QID85,Are you using AI agents in your work (developm...,MC,NaN,NaN
AIComplex,QID81,How well do the AI tools you use in your devel...,MC,NaN,NaN
AIExplain,QID84,"In your own words, is &quot;vibe coding&quot; ...",TE,NaN,NaN
AIFrustration,QID99,"When using AI tools, which of the following pr...",MC,NaN,NaN
AIHuman,QID100,"In the future, if AI can do most coding tasks,...",MC,NaN,NaN
AILearnHow,QID32,How did you learn to code for AI in the past y...,MC,NaN,NaN
AIModels,QID43,Which <b>LLM models for AI tools</b> have you ...,Matrix,NaN,NaN
AIModelsChoice,QID50,Did you utilize or integrate specific Large La...,MC,NaN,NaN
AIModelsHaveEntry,QID68,Was the LLM model for AI tools you use not lis...,TE,NaN,NaN
AIModelsWantEntry,QID69,Was the LLM model for AI tools you want to use...,TE,NaN,NaN
AIOpen,QID93,"Looking ahead 3–5 years, what skills do you be...",TE,NaN,NaN
AISelect,QID78,Do you currently use AI tools in your developm...,MC,NaN,NaN
AISent,QID79,How favorable is your stance on using AI tools...,MC,NaN,NaN
AIThreat,QID28,Do you believe AI is a threat to your current ...,MC,NaN,NaN
AITool,QID82,Which parts of your development workflow are y...,Matrix,NaN,NaN
Age,QID4,What is your age?,MC,NaN,NaN
AgentUsesGeneral,QID106,,MC,NaN,NaN
CommPlatform,QID42,Which <b>community platforms</b> have you util...,Matrix,NaN,NaN
CommPlatformHaveEntr,QID66,Was the community platform you use not listed ...,TE,NaN,NaN
CommPlatformWantEntr,QID67,Was the community platform you want to use not...,TE,NaN,NaN
CompTotal,QID22,What is your current total <b>annual</b> compe...,TE,NaN,NaN
Country,QID20,Where do you live?,MC,NaN,NaN
Currency,QID21,Which currency do you use day-to-day? If your ...,MC,NaN,NaN
Database,QID35,Which <b>database environments </b>have you do...,Matrix,NaN,NaN
DatabaseChoice,QID45,Did you work with database environments in the...,MC,NaN,NaN
DatabaseHaveEntry,QID54,Was the database environment you use not liste...,TE,NaN,NaN
DatabaseWantEntry,QID55,Was the database environment you want to use n...,TE,NaN,NaN
DevEnvHaveEntry,QID60,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvWantEntry,QID61,Was the developer environment or AI-enabled co...,TE,NaN,NaN
DevEnvs,QID38,Which <strong>development environments and AI-...,Matrix,NaN,NaN
DevEnvsChoice,QID48,Did you work with development environments or ...,MC,NaN,NaN
DevType,QID15,Which of the following describes your current ...,MC,NaN,NaN
EdLevel,QID9,Which of the following best describes the high...,MC,NaN,NaN
Employment,QID7,Which of the following best describes your cur...,MC,NaN,NaN
EmploymentAddl,QID8,Which of the following <strong>additional</str...,MC,NaN,NaN
ICorPM,QID23,Are you an individual contributor or people ma...,MC,NaN,NaN
Industry,QID25,What industry do you work for in?,MC,NaN,NaN
JobSat,QID26,How satisfied are you in your current professi...,MC,NaN,NaN
JobSatPoints_1,QID27,Rank the following attributes of your current ...,RO,Control over the level of quality in projects,1.0
JobSatPoints_10,QID27,Rank the following attributes of your current ...,RO,Working with new technologies and tools,11.0
JobSatPoints_11,QID27,Rank the following attributes of your current ...,RO,Competitive pay and benefits,12.0
JobSatPoints_13,QID27,Rank the following attributes of your current ...,RO,Recognition from peers for your work,13.0
JobSatPoints_14,QID27,Rank the following attributes of your current ...,RO,Recognition from leadership for your work,14.0
JobSatPoints_15,QID27,Rank the following attributes of your current ...,RO,Other (please specify):,15.0
JobSatPoints_15_TEXT,QID27,Rank the following attributes of your current ...,RO,Other (please specify): - Text,15.0
JobSatPoints_16,QID27,Rank the following attributes of your current ...,RO,You like your manager,3.0
JobSatPoints_2,QID27,Rank the following attributes of your current ...,RO,Autonomy and trust to manage your own tasks,2.0
JobSatPoints_3,QID27,Rank the following attributes of your current ...,RO,Collaboration and support from a team,4.0
JobSatPoints_4,QID27,Rank the following attributes of your current ...,RO,Expert mentors,5.0
JobSatPoints_5,QID27,Rank the following attributes of your current ...,RO,Opportunities to mentor and lead junior-level ...,6.0
JobSatPoints_6,QID27,Rank the following attributes of your current ...,RO,Developing specialized expertise,7.0
JobSatPoints_7,QID27,Rank the following attributes of your current ...,RO,Solving real-world problems,8.0
JobSatPoints_8,QID27,Rank the following attributes of your current ...,RO,Job stability and career growth with a single ...,9.0
JobSatPoints_9,QID27,Rank the following attributes of your current ...,RO,Innovation through solving challenging and com...,10.0
Language,QID34,"Which <b>programming, scripting, and markup la...",Matrix,NaN,NaN
LanguageChoice,QID44,"Did you work with programming, scripting and m...",MC,NaN,NaN
LanguagesHaveEntry,QID51,Was the programming language you use not liste...,TE,NaN,NaN
LanguagesWantEntry,QID52,Was the programming language you want to use n...,TE,NaN,NaN
LearnCode,QID11,How did you learn to code in the past year? Se...,MC,NaN,NaN
LearnCodeAI,QID12,Did you spend time in the last year learning A...,MC,NaN,NaN
LearnCodeChoose,QID10,Did you begin learning to code or learn a new ...,MC,NaN,NaN
MainBranch,QID3,Are you someone who writes code? Please select...,MC,NaN,NaN
NewRole,QID29,Have you considered a career change or transit...,MC,NaN,NaN
OfficeStackAsync,QID41,Which <b>collaborative work management and/or ...,Matrix,NaN,NaN
OfficeStackHaveEntry,QID64,Was the collaborative work management and/or c...,TE,NaN,NaN
OfficeStackWantEntry,QID65,Was the collaborative work management and/or c...,TE,NaN,NaN
OpSys,QID40,What is the primary <b>operating system</b> in...,Matrix,NaN,NaN
OrgSize,QID16,Approximately how many people are employed by ...,MC,NaN,NaN
Platform,QID36,"Which <b>cloud platforms, containerization/orc...",Matrix,NaN,NaN
PlatformChoice,QID46,"Did you work with cloud platforms, containeriz...",MC,NaN,NaN
PlatformHaveEntry,QID56,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PlatformWantEntry,QID57,"Was the cloud platforms, containerization/orch...",TE,NaN,NaN
PurchaseInfluence,QID17,Have you <strong>influenced or endorsed</stron...,MC,NaN,NaN
RemoteWork,QID24,Which best describes your current work situation?,MC,NaN,NaN
SOAccount,QID72,Do you have a Stack Overflow account?,MC,NaN,NaN
SOComm,QID77,Do you consider yourself a member of the Stack...,MC,NaN,NaN
SODuration,QID71,How long have you used Stack Overflow?,MC,NaN,NaN
SOFriction,QID97,"When you visit Stack Overflow, how often is it...",MC,NaN,NaN
SOPartFreq,QID73,How frequently would you say you participate i...,MC,NaN,NaN
SOTags,QID39,Which rising technology of the added as <b>new...,Matrix,NaN,NaN
SOTagsHaveEntry,QID62,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOTagsWant Entry,QID63,Was the new tag on Stack Overflow (i.e. added ...,TE,NaN,NaN
SOVisitFreq,QID70,How frequently would you say you visit Stack O...,MC,NaN,NaN
SO_Actions_1,QID76,"When visiting Stack Overflow, which following ...",RO,Browse content related to Q&A posts I recently...,1.0
SO_Actions_10,QID76,"When visiting Stack Overflow, which following ...",RO,Use discussion or chat feature,9.0
SO_Actions_15,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in):,10.0
SO_Actions_15_TEXT,QID76,"When visiting Stack Overflow, which following ...",RO,Other (write in): - Text,15.0
SO_Actions_16,QID76,"When visiting Stack Overflow, which following ...",RO,Read and/or vote on comments for a Question or...,2.0
SO_Actions_3,QID76,"When visiting Stack Overflow, which following ...",RO,Bookmark posts to look at later,3.0
SO_Actions_4,QID76,"When visiting Stack Overflow, which following ...",RO,"Directly open a Q&A post via search, documenta...",4.0
SO_Actions_5,QID76,"When visiting Stack Overflow, which following ...",RO,Ask a question,5.0
SO_Actions_6,QID76,"When visiting Stack Overflow, which following ...",RO,Answer a question,6.0
SO_Actions_7,QID76,"When visiting Stack Overflow, which following ...",RO,Upvote/Downvote Q&A posts,8.0
SO_Actions_9,QID76,"When visiting Stack Overflow, which following ...",RO,Comment on Q&A posts,7.0
SO_Dev_Content,QID75,"Whether it be to solve a problem, for career g...",MC,NaN,NaN
TechEndorseIntro,QID33,When you&rsquo;re in a position to <strong>inf...,MC,NaN,NaN
TechEndorse_1,QID18,What attracts you to a technology or causes yo...,RO,AI integration or AI Agent capabilities,1.0
TechEndorse_13,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify):,10.0
TechEndorse_13_TEXT,QID18,What attracts you to a technology or causes yo...,RO,Other (please specify): - Text,13.0
TechEndorse_2,QID18,What attracts you to a technology or causes yo...,RO,Easy-to-use API,2.0
TechEndorse_3,QID18,What attracts you to a technology or causes yo...,RO,Robust and complete API,3.0
TechEndorse_4,QID18,What attracts you to a technology or causes yo...,RO,Customizable and manageable codebase,4.0
TechEndorse_5,QID18,What attracts you to a technology or causes yo...,RO,Reputation for quality,5.0
TechEndorse_6,QID18,What attracts you to a technology or causes yo...,RO,Connected to an open-source project,6.0
TechEndorse_7,QID18,What attracts you to a technology or causes yo...,RO,Good brand and public image,7.0
TechEndorse_8,QID18,What attracts you to a technology or causes yo...,RO,Reliability and low latency,8.0
TechEndorse_9,QID18,What attracts you to a technology or causes yo...,RO,Costs are manageable,9.0
TechOppose_1,QID19,What would turn you off or cause you to reject...,RO,Lack of AI or AI agents,1.0
TechOppose_11,QID19,What would turn you off or cause you to reject...,RO,Availability of better alternatives,7.0
TechOppose_13,QID19,What would turn you off or cause you to reject...,RO,Outdated or obsolete technology or features,8.0
TechOppose_15,QID19,What would turn you off or cause you to reject...,RO,Other (please specify):,10.0
TechOppose_15_TEXT,QID19,What would turn you off or cause you to reject...,RO,Other (please specify): - Text,15.0
TechOppose_16,QID19,What would turn you off or cause you to reject...,RO,Ethical concerns,9.0
TechOppose_2,QID19,What would turn you off or cause you to reject...,RO,Poor usability,2.0
TechOppose_3,QID19,What would turn you off or cause you to reject...,RO,Lack of or sub-par API,3.0
TechOppose_5,QID19,What would turn you off or cause you to reject...,RO,Inefficient or time-costly,4.0
TechOppose_7,QID19,What would turn you off or cause you to reject...,RO,Prohibitive pricing,5.0
TechOppose_9,QID19,What would turn you off or cause you to reject...,RO,Security or privacy concerns,6.0
ToolCountPersonal,QID31,<b></b>For your <b>side projects or other pers...,TE,NaN,NaN
ToolCountWork,QID30,"For your <b>primary work role</b> (student, de...",TE,NaN,NaN
Webframe,QID37,Which <b>web frameworks and web technologies</...,Matrix,NaN,NaN
WebframeChoice,QID47,Did you work with web frameworks and web techn...,MC,NaN,NaN
WebframeHaveEntry,QID58,Were the web frameworks and web technologies y...,TE,NaN,NaN
WebframeWantEntry,QID59,Were the web frameworks and web technologies y...,TE,NaN,NaN
WorkExp,QID14,How many years of professional work experience...,TE,NaN,NaN
YearsCode,QID13,"Including any education, how many years have y...",TE,NaN,NaN

In [64]:
schema_df.loc['SO_Actions_1', 'question']

'When visiting Stack Overflow, which following activities are you most interested in?  Please rank the following so the first activity is what most interests you and last is your least interested activity.'

In [65]:
df['SO_Actions_1'].count()

np.int64(26260)

In [66]:
df['SO_Actions_1'].value_counts()

SO_Actions_1
2.0     4032
3.0     3791
4.0     2969
7.0     2778
8.0     2611
6.0     2582
5.0     2566
9.0     2153
1.0     2138
10.0     217
11.0     129
12.0     110
13.0      97
14.0      79
15.0       8
Name: count, dtype: int64

In [67]:
df['SO_Actions_1']

ResponseId
34268    NaN
28701    3.0
43144    9.0
35354    8.0
45972    NaN
        ...
49186    NaN
49187    NaN
49188    NaN
49190    NaN
49191    NaN
Name: SO_Actions_1, Length: 49191, dtype: float64

In [68]:
df['Country'].value_counts().head(10)

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
Canada                                                  1305
Ukraine                                                  964
Poland                                                   888
Netherlands                                              867
Italy                                                    835
Name: count, dtype: int64

In [69]:
df['Country']

ResponseId
34268        United States of America
28701                         Ukraine
43144                          Poland
35354    Iran, Islamic Republic of...
45972                     Netherlands
                     ...
49186                             NaN
49187                             NaN
49188                             NaN
49190                             NaN
49191                             NaN
Name: Country, Length: 49191, dtype: str

In [70]:
schema_df.loc['SOTags', 'question']

'Which rising technology of the added as <b>new tag or tag subject area on Stack Overflow</b> in the last three years <strong>have you used</strong> regularly in the past year, and which do you <strong>want to work with</strong> over the next year? Please check all that apply.<br>\n '

In [71]:
df['SOAccount'].count()

np.int64(32797)

In [72]:
filt = df['Country'] == 'United States of America'
df[filt][['SOAccount', 'Country']]

                          SOAccount                   Country
ResponseId
34268                           NaN  United States of America
10026                            No  United States of America
28059                           Yes  United States of America
5411                            Yes  United States of America
34976                           Yes  United States of America
...                             ...                       ...
49126       Not sure/can't remember  United States of America
49128                           Yes  United States of America
49146                           Yes  United States of America
49158                           NaN  United States of America
49178                            No  United States of America

[7233 rows x 2 columns]

In [73]:
filt = df['Country'] == 'Nigeria'
df.loc[filt]['SOAccount'].value_counts()

SOAccount
Yes                        134
No                          21
Not sure/can't remember     11
Name: count, dtype: int64

In [74]:
country_grp = df.groupby('Country')

In [75]:
country_grp['SOAccount'].value_counts().head(40)

Country              SOAccount
Afghanistan          Yes                          8
                     No                           1
Albania              Yes                         18
                     Not sure/can't remember      3
Algeria              Yes                         35
                     No                           3
                     Not sure/can't remember      3
Andorra              Yes                          4
                     No                           1
Angola               Yes                          4
                     Not sure/can't remember      1
Antigua and Barbuda  Yes                          1
Argentina            Yes                        171
                     No                          32
                     Not sure/can't remember      9
Armenia              Yes                         20
                     Not sure/can't remember      1
                     No                           1
Australia            Yes                        638
                     No                          86
                     Not sure/can't remember     39
Austria              Yes                        321
                     No                          51
                     Not sure/can't remember     19
Azerbaijan           Yes                         14
                     No                           1
Bahrain              Yes                          4
                     Not sure/can't remember      1
Bangladesh           Yes                        177
                     No                           8
                     Not sure/can't remember      3
Barbados             Yes                          3
                     No                           1
Belarus              Yes                         24
                     No                           1
Belgium              Yes                        252
                     No                          30
                     Not sure/can't remember     26
Belize               Yes                          1
Benin                Yes                          3
Name: count, dtype: int64

In [76]:
country_grp['SalaryUSD'].mean().head(20)

Country
Afghanistan             12227.250000
Albania                 47973.583333
Algeria                 15935.400000
Andorra                208763.750000
Angola                 149857.250000
Antigua and Barbuda         1.000000
Argentina               46271.187500
Armenia                 25016.363636
Australia              115941.413005
Austria                 79477.625000
Azerbaijan              31202.333333
Bahrain                 74240.500000
Bangladesh              15520.941667
Barbados                45450.500000
Belarus                 58267.312500
Belgium                 84666.275229
Belize                 102121.000000
Benin                    6816.333333
Bhutan                  20361.000000
Bolivia                 25214.307692
Name: SalaryUSD, dtype: float64

In [77]:
country_grp['SalaryUSD'].mean().loc['Nigeria']

np.float64(63181.8431372549)

In [78]:
country_grp['SalaryUSD'].agg(['mean', 'median'])

                                               mean    median
Country
Afghanistan                            12227.250000    6121.0
Albania                                47973.583333   26269.0
Algeria                                15935.400000    6472.0
Andorra                               208763.750000  200125.5
Angola                                149857.250000    9578.0
...                                             ...       ...
Venezuela, Bolivarian Republic of...   17008.400000    9000.0
Viet Nam                              189894.192982    7642.0
Yemen                                  17582.500000    5545.5
Zambia                                  6594.875000    1966.5
Zimbabwe                               25662.500000   17500.0

[177 rows x 2 columns]

In [79]:
country_grp['SalaryUSD'].agg(['mean', 'median']).loc['Nigeria']

mean      63181.843137
median     1291.000000
Name: Nigeria, dtype: float64

In [80]:
NUMpython_user = country_grp['LanguageHaveWorkedWith'].apply(lambda x: x.str.contains('Python').sum())

In [81]:
NUMpython_user

Country
Afghanistan                              4
Albania                                 10
Algeria                                 23
Andorra                                  2
Angola                                   1
                                        ..
Venezuela, Bolivarian Republic of...    23
Viet Nam                                78
Yemen                                    6
Zambia                                   7
Zimbabwe                                 7
Name: LanguageHaveWorkedWith, Length: 177, dtype: int64

In [82]:
Num_users = df['Country'].value_counts()

In [83]:
Num_users

Country
United States of America                                7233
Germany                                                 3025
India                                                   2547
United Kingdom of Great Britain and Northern Ireland    2042
France                                                  1409
                                                        ...
Guinea-Bissau                                              1
Niger                                                      1
Palau                                                      1
San Marino                                                 1
Timor-Leste                                                1
Name: count, Length: 177, dtype: int64

In [84]:
PCT_python_users = (NUMpython_user /Num_users) * 100

In [85]:
PCT_python_users

Country
Afghanistan                             30.769231
Albania                                 45.454545
Algeria                                 46.938776
Andorra                                 33.333333
Angola                                  14.285714
                                          ...
Venezuela, Bolivarian Republic of...    48.936170
Viet Nam                                53.793103
Yemen                                   33.333333
Zambia                                  53.846154
Zimbabwe                                53.846154
Length: 177, dtype: float64

In [86]:
df_pyth = pd.concat([Num_users, NUMpython_user], axis='columns', sort=False)
df_pyth

,count,LanguageHaveWorkedWith
Country,,
United States of America,7233,4221
Germany,3025,1685
India,2547,1162
United Kingdom of Great Britain and Northern Ireland,2042,1027
France,1409,820
...,...,...
Guinea-Bissau,1,1
Niger,1,1
Palau,1,1
San Marino,1,0
Timor-Leste,1,0

In [87]:
df_pyth.rename(columns = {'count': 'Num_users', 'LanguageHaveWorkedWith': 'NUMpython_user'}, inplace=True)

In [88]:
df_pyth['PCT_python_users'] = (NUMpython_user/Num_users) * 100

In [89]:
df_pyth.columns = (x.lower() for x in df_pyth.columns)
df_pyth

,num_users,numpython_user,pct_python_users
Country,,,
United States of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
...,...,...,...
Guinea-Bissau,1,1,100.000000
Niger,1,1,100.000000
Palau,1,1,100.000000
San Marino,1,0,0.000000
Timor-Leste,1,0,0.000000

In [90]:
df_pyth['Country'] = df['Country'].str.lower()
df_pyth

,num_users,numpython_user,pct_python_users,Country
Country,,,,
United States of America,7233,4221,58.357528,NaN
Germany,3025,1685,55.702479,NaN
India,2547,1162,45.622301,NaN
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830,NaN
France,1409,820,58.197303,NaN
...,...,...,...,...
Guinea-Bissau,1,1,100.000000,NaN
Niger,1,1,100.000000,NaN
Palau,1,1,100.000000,NaN
San Marino,1,0,0.000000,NaN
Timor-Leste,1,0,0.000000,NaN

In [91]:
df_pyth.drop(columns = 'Country', inplace=True)

In [92]:
df_pyth.head()

,num_users,numpython_user,pct_python_users
Country,,,
United States of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303

In [93]:
df_pyth

,num_users,numpython_user,pct_python_users
Country,,,
United States of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom of Great Britain and Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
...,...,...,...
Guinea-Bissau,1,1,100.000000
Niger,1,1,100.000000
Palau,1,1,100.000000
San Marino,1,0,0.000000
Timor-Leste,1,0,0.000000

In [94]:
df_pyth.index = df_pyth.index.str.lower()

In [95]:
df_pyth.reset_index(inplace=True)

In [96]:
df_pyth

,Country,num_users,numpython_user,pct_python_users
0,united states of america,7233,4221,58.357528
1,germany,3025,1685,55.702479
2,india,2547,1162,45.622301
3,united kingdom of great britain and northern i...,2042,1027,50.293830
4,france,1409,820,58.197303
...,...,...,...,...
172,guinea-bissau,1,1,100.000000
173,niger,1,1,100.000000
174,palau,1,1,100.000000
175,san marino,1,0,0.000000
176,timor-leste,1,0,0.000000

In [97]:
df_pyth['Country'] = df_pyth['Country'].str.upper()

In [98]:
df_pyth

,Country,num_users,numpython_user,pct_python_users
0,UNITED STATES OF AMERICA,7233,4221,58.357528
1,GERMANY,3025,1685,55.702479
2,INDIA,2547,1162,45.622301
3,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,2042,1027,50.293830
4,FRANCE,1409,820,58.197303
...,...,...,...,...
172,GUINEA-BISSAU,1,1,100.000000
173,NIGER,1,1,100.000000
174,PALAU,1,1,100.000000
175,SAN MARINO,1,0,0.000000
176,TIMOR-LESTE,1,0,0.000000

In [99]:
df_pyth.columns = (x.lower() for x in df_pyth.columns)

In [100]:
df_pyth

,country,num_users,numpython_user,pct_python_users
0,UNITED STATES OF AMERICA,7233,4221,58.357528
1,GERMANY,3025,1685,55.702479
2,INDIA,2547,1162,45.622301
3,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,2042,1027,50.293830
4,FRANCE,1409,820,58.197303
...,...,...,...,...
172,GUINEA-BISSAU,1,1,100.000000
173,NIGER,1,1,100.000000
174,PALAU,1,1,100.000000
175,SAN MARINO,1,0,0.000000
176,TIMOR-LESTE,1,0,0.000000

In [101]:
df_pyth.columns =  df_pyth.columns.str.title()

In [102]:
df_pyth

,Country,Num_Users,Numpython_User,Pct_Python_Users
0,UNITED STATES OF AMERICA,7233,4221,58.357528
1,GERMANY,3025,1685,55.702479
2,INDIA,2547,1162,45.622301
3,UNITED KINGDOM OF GREAT BRITAIN AND NORTHERN I...,2042,1027,50.293830
4,FRANCE,1409,820,58.197303
...,...,...,...,...
172,GUINEA-BISSAU,1,1,100.000000
173,NIGER,1,1,100.000000
174,PALAU,1,1,100.000000
175,SAN MARINO,1,0,0.000000
176,TIMOR-LESTE,1,0,0.000000

In [103]:
df_pyth['Country'] =  df_pyth['Country'].str.title()

In [104]:
df_pyth

,Country,Num_Users,Numpython_User,Pct_Python_Users
0,United States Of America,7233,4221,58.357528
1,Germany,3025,1685,55.702479
2,India,2547,1162,45.622301
3,United Kingdom Of Great Britain And Northern I...,2042,1027,50.293830
4,France,1409,820,58.197303
...,...,...,...,...
172,Guinea-Bissau,1,1,100.000000
173,Niger,1,1,100.000000
174,Palau,1,1,100.000000
175,San Marino,1,0,0.000000
176,Timor-Leste,1,0,0.000000

In [105]:
df_pyth.sort_values(by =  'Pct_Python_Users', ascending=False).head(20)

,Country,Num_Users,Numpython_User,Pct_Python_Users
174,Palau,1,1,100.000000
154,Suriname,2,2,100.000000
155,Mali,2,2,100.000000
152,Saint Lucia,2,2,100.000000
147,Mongolia,3,3,100.000000
167,Lesotho,1,1,100.000000
168,Guinea,1,1,100.000000
171,Gambia,1,1,100.000000
156,Haiti,2,2,100.000000
173,Niger,1,1,100.000000
172,Guinea-Bissau,1,1,100.000000
169,Cape Verde,1,1,100.000000
145,Democratic People'S Republic Of Korea,4,3,75.000000
117,Cuba,8,6,75.000000
112,Panama,10,7,70.000000
91,Malta,19,13,68.421053
132,Kosovo,6,4,66.666667
151,Brunei Darussalam,3,2,66.666667
148,Bhutan,3,2,66.666667
108,Mauritius,11,7,63.636364

In [106]:
filt = df_pyth['Country'] == 'Nigeria'
df_pyth.loc[filt]

    Country  Num_Users  Numpython_User  Pct_Python_Users
38  Nigeria        199              80         40.201005

In [107]:
df_pyth.set_index('Country', inplace = True)

In [108]:
df_pyth

,Num_Users,Numpython_User,Pct_Python_Users
Country,,,
United States Of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom Of Great Britain And Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
...,...,...,...
Guinea-Bissau,1,1,100.000000
Niger,1,1,100.000000
Palau,1,1,100.000000
San Marino,1,0,0.000000
Timor-Leste,1,0,0.000000

In [109]:
df_pyth.loc['Nigeria']

Num_Users           199.000000
Numpython_User       80.000000
Pct_Python_Users     40.201005
Name: Nigeria, dtype: float64

In [110]:
filt = df_pyth['Numpython_User'] == 80
df_pyth.loc[filt]

         Num_Users  Numpython_User  Pct_Python_Users
Country
Nigeria        199              80         40.201005

In [111]:
df['EdLevel'].value_counts()

EdLevel
Bachelor’s degree (B.A., B.S., B.Eng., etc.)                                          20278
Master’s degree (M.A., M.S., M.Eng., MBA, etc.)                                       12589
Some college/university study without earning a degree                                 6182
Secondary school (e.g. American high school, German Realschule or Gymnasium, etc.)     3631
Professional degree (JD, MD, Ph.D, Ed.D, etc.)                                         2624
Associate degree (A.A., A.S., etc.)                                                    1562
Other (please specify):                                                                 701
Primary/elementary school                                                               582
Name: count, dtype: int64

In [112]:
df['EdLevel'].mode()

0    Bachelor’s degree (B.A., B.S., B.Eng., etc.)
Name: EdLevel, dtype: str

In [113]:
country_grp['SalaryUSD'].mean()

Country
Afghanistan                              12227.250000
Albania                                  47973.583333
Algeria                                  15935.400000
Andorra                                 208763.750000
Angola                                  149857.250000
                                            ...
Venezuela, Bolivarian Republic of...     17008.400000
Viet Nam                                189894.192982
Yemen                                    17582.500000
Zambia                                    6594.875000
Zimbabwe                                 25662.500000
Name: SalaryUSD, Length: 177, dtype: float64

In [114]:
df.nlargest(2, 'SalaryUSD')['Country']

ResponseId
34268    United States of America
28701                     Ukraine
Name: Country, dtype: str

In [115]:
filt = df['SalaryUSD'].nlargest(15).index
df.loc[filt]['Country']

ResponseId
34268                             United States of America
28701                                              Ukraine
43144                                               Poland
35354                         Iran, Islamic Republic of...
45972                                          Netherlands
48429                                              Ukraine
24901                                                India
10026                             United States of America
37353                                              Ukraine
30729                                               Brazil
40419                                             Viet Nam
19537                                              Nigeria
28056                                         South Africa
14874    United Kingdom of Great Britain and Northern I...
48024                                            Australia
Name: Country, dtype: str

In [116]:
df.sort_values(by = 'SalaryUSD', ascending=False)[['SalaryUSD', 'WorkExp', 'WorkExp']].head(12)

             SalaryUSD  WorkExp  WorkExp
ResponseId
34268       50000000.0     10.0     10.0
28701       33552715.0     20.0     20.0
43144       18387548.0     10.0     10.0
35354       15430267.0     15.0     15.0
45972       13921760.0     30.0     30.0
48429       10000000.0      NaN      NaN
24901        9531653.0      1.0      1.0
10026        9000000.0      2.0      2.0
37353        6890299.0     15.0     15.0
30729        6371285.0     17.0     17.0
40419        6000000.0     10.0     10.0
19537        5810837.0     20.0     20.0

In [117]:
df.sort_values(by = 'WorkExp', ascending=False)[['SalaryUSD', 'WorkExp']].head(20)

            SalaryUSD  WorkExp
ResponseId
25195             NaN    100.0
45803             NaN    100.0
25121             NaN    100.0
28951             NaN    100.0
26559             NaN    100.0
15656             NaN    100.0
36625           182.0    100.0
38103            73.0    100.0
29192             NaN    100.0
12141           100.0    100.0
11065           100.0    100.0
29037             NaN    100.0
7882              NaN    100.0
44527             NaN    100.0
4934              NaN    100.0
16716        336327.0    100.0
43980             NaN    100.0
43619             NaN    100.0
22687             NaN    100.0
40983             NaN    100.0

In [118]:
schema_df.loc['WorkExp', 'question']

"How many years of professional work experience do you have? Please round to the nearest whole number, excluding any decimal points.  If your answer is '0', please leave blank."

In [119]:
df.sort_values(by = 'SalaryUSD', ascending=False)[['SalaryUSD', 'LanguageHaveWorkedWith']].head(12)

             SalaryUSD                             LanguageHaveWorkedWith
ResponseId
34268       50000000.0                                                NaN
28701       33552715.0              C#;HTML/CSS;JavaScript;SQL;TypeScript
43144       18387548.0                                                NaN
35354       15430267.0                                                NaN
45972       13921760.0                                        Java;Kotlin
48429       10000000.0  Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...
24901        9531653.0            HTML/CSS;Java;JavaScript;SQL;TypeScript
10026        9000000.0                                                NaN
37353        6890299.0            HTML/CSS;JavaScript;Ruby;SQL;TypeScript
30729        6371285.0    Bash/Shell (all shells);Elixir;Go;Kotlin;Python
40419        6000000.0  Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...
19537        5810837.0  Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...

In [120]:
df_lang  = df['LanguageHaveWorkedWith'].str.split(';').explode().value_counts()

In [121]:
df['LanguageHaveWorkedWith'].str.split(';').explode()

ResponseId
34268           NaN
28701            C#
28701      HTML/CSS
28701    JavaScript
28701           SQL
            ...
49186           NaN
49187           NaN
49188           NaN
49190           NaN
49191           NaN
Name: LanguageHaveWorkedWith, Length: 212104, dtype: str

In [122]:
df_lang.sort_values().nlargest(10)

LanguageHaveWorkedWith
JavaScript                 21005
HTML/CSS                   19698
SQL                        18633
Python                     18410
Bash/Shell (all shells)    15503
TypeScript                 13859
Java                        9358
C#                          8852
C++                         7485
PowerShell                  7371
Name: count, dtype: int64

In [123]:
df_pyth.columns = df_pyth.columns.str.strip().str.lower()

In [124]:
df_pyth

,num_users,numpython_user,pct_python_users
Country,,,
United States Of America,7233,4221,58.357528
Germany,3025,1685,55.702479
India,2547,1162,45.622301
United Kingdom Of Great Britain And Northern Ireland,2042,1027,50.293830
France,1409,820,58.197303
...,...,...,...
Guinea-Bissau,1,1,100.000000
Niger,1,1,100.000000
Palau,1,1,100.000000
San Marino,1,0,0.000000
Timor-Leste,1,0,0.000000

In [125]:
df= df.dropna(subset= ['LanguageHaveWorkedWith', 'Country'])

In [126]:
df_lang = df[['LanguageHaveWorkedWith', 'Country']].copy()
df_lang

                                       LanguageHaveWorkedWith      Country
ResponseId
28701                   C#;HTML/CSS;JavaScript;SQL;TypeScript      Ukraine
45972                                             Java;Kotlin  Netherlands
48429       Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...      Ukraine
24901                 HTML/CSS;Java;JavaScript;SQL;TypeScript        India
37353                 HTML/CSS;JavaScript;Ruby;SQL;TypeScript      Ukraine
...                                                       ...          ...
484         Bash/Shell (all shells);HTML/CSS;JavaScript;PH...     Zimbabwe
4062          Bash/Shell (all shells);C++;PowerShell;Python;R     Zimbabwe
13949                                     HTML/CSS;Python;SQL     Zimbabwe
41124                                             Java;Python     Zimbabwe
41192                                                   R;SQL     Zimbabwe

[31671 rows x 2 columns]

In [127]:
df_lang['language'] = df_lang['LanguageHaveWorkedWith'].str.split(';').explode('language')

In [128]:
df_lang.columns = df_lang.columns.str.lower()
df_lang

,languagehaveworkedwith,country,language
ResponseId,,,
28701,C#;HTML/CSS;JavaScript;SQL;TypeScript,Ukraine,Bash/Shell (all shells)
45972,Java;Kotlin,Netherlands,JavaScript
48429,Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...,Ukraine,SQL
24901,HTML/CSS;Java;JavaScript;SQL;TypeScript,India,Java
37353,HTML/CSS;JavaScript;Ruby;SQL;TypeScript,Ukraine,Python
...,...,...,...
484,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Zimbabwe,Bash/Shell (all shells)
4062,Bash/Shell (all shells);C++;PowerShell;Python;R,Zimbabwe,C
13949,HTML/CSS;Python;SQL,Zimbabwe,Bash/Shell (all shells)
41124,Java;Python,Zimbabwe,HTML/CSS
41192,R;SQL,Zimbabwe,Python

In [129]:
df_lang['language'] = df['LanguageHaveWorkedWith'].str.split(';').explode('language')
df_lang['country'] = df['Country']
df_lang

,languagehaveworkedwith,country,language
ResponseId,,,
28701,C#;HTML/CSS;JavaScript;SQL;TypeScript,Ukraine,Bash/Shell (all shells)
45972,Java;Kotlin,Netherlands,JavaScript
48429,Assembly;C#;GDScript;HTML/CSS;JavaScript;Micro...,Ukraine,SQL
24901,HTML/CSS;Java;JavaScript;SQL;TypeScript,India,Java
37353,HTML/CSS;JavaScript;Ruby;SQL;TypeScript,Ukraine,Python
...,...,...,...
484,Bash/Shell (all shells);HTML/CSS;JavaScript;PH...,Zimbabwe,Bash/Shell (all shells)
4062,Bash/Shell (all shells);C++;PowerShell;Python;R,Zimbabwe,C
13949,HTML/CSS;Python;SQL,Zimbabwe,Bash/Shell (all shells)
41124,Java;Python,Zimbabwe,HTML/CSS
41192,R;SQL,Zimbabwe,Python

In [130]:
lang_by_country = df_lang.groupby(['language', 'country']).size().reset_index(name='count')

In [131]:
lang_by_country.head(25)

    language                                            country  count
0        Ada                                          Australia      1
1        Ada                                            Austria      1
2        Ada                                             Canada      1
3        Ada                                     Czech Republic      2
4        Ada                                             France      2
5        Ada                                            Germany      5
6        Ada                                 Hong Kong (S.A.R.)      1
7        Ada                                              Italy      2
8        Ada                                              Japan      1
9        Ada                                        Netherlands      1
10       Ada                                             Norway      1
11       Ada                                           Pakistan      1
12       Ada                                             Poland      1
13       Ada                                            Romania      1
14       Ada                                           Slovenia      1
15       Ada                                              Spain      2
16       Ada                                             Sweden      3
17       Ada                                        Switzerland      2
18       Ada  United Kingdom of Great Britain and Northern I...      4
19       Ada                           United States of America      6
20  Assembly                                            Albania      1
21  Assembly                                          Australia      3
22  Assembly                                            Austria      2
23  Assembly                                         Bangladesh      2
24  Assembly                                            Belgium      5

In [132]:
top_country_lang = lang_by_country.sort_values(['country', 'count'], ascending = [True, False]).groupby('country').head(1)

In [133]:
top_country_lang

                     language                               country  count
940                  HTML/CSS                           Afghanistan      2
941                  HTML/CSS                               Albania      4
942                  HTML/CSS                               Algeria      6
298                        C#                               Andorra      2
877                    Groovy                                Angola      1
...                       ...                                   ...    ...
1962                   Python  Venezuela, Bolivarian Republic of...      9
1284               JavaScript                              Viet Nam     17
1060                 HTML/CSS                                 Yemen      3
2297                      SQL                                Zambia      3
198   Bash/Shell (all shells)                              Zimbabwe      2

[174 rows x 3 columns]

In [134]:
pivot = lang_by_country.pivot(index= 'country', columns='language', values='count').fillna(0)
pivot

language,Ada,Assembly,Bash/Shell (all shells),C,C#,C++,COBOL,Dart,Delphi,Elixir,Erlang,F#,Fortran,GDScript,Gleam,Go,Groovy,HTML/CSS,Java,JavaScript,Kotlin,Lisp,Lua,MATLAB,MicroPython,Mojo,OCaml,PHP,Perl,PowerShell,Prolog,Python,R,Ruby,Rust,SQL,Scala,Swift,TypeScript,VBA,Visual Basic (.Net),Zig
country,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
Afghanistan,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0
Albania,0.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,4.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
Algeria,0.0,0.0,5.0,1.0,2.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,0.0,6.0,2.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0
Andorra,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Angola,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"Venezuela, Bolivarian Republic of...",0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,1.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,9.0,0.0,2.0,2.0,5.0,2.0,2.0,6.0,0.0,0.0,0.0
Viet Nam,0.0,1.0,13.0,1.0,6.0,3.0,0.0,3.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,3.0,1.0,11.0,5.0,17.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0,11.0,0.0,3.0,5.0,14.0,0.0,2.0,8.0,0.0,1.0,1.0
Yemen,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,0.0,3.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0
Zambia,0.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,1.0,0.0,1.0,0.0,1.0,0.0
Zimbabwe,0.0,0.0,2.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0

In [135]:
top_lang_by_country = lang_by_country.sort_values(by=['country', 'count'], ascending = [True, False]).groupby('country').head(2)

In [136]:
top_lang_by_country.tail(2)

                    language   country  count
198  Bash/Shell (all shells)  Zimbabwe      2
294                        C  Zimbabwe      2

In [137]:
df_na = df[['LearnCode', 'TechEndorseIntro', 'ToolCountWork', 'Country']].copy()

In [138]:
df_na

,LearnCode,TechEndorseIntro,ToolCountWork,Country
ResponseId,,,,
28701,NaN,Work,10.0,Ukraine
45972,Colleague or on-the-job training,Work,NaN,Netherlands
48429,"Other online resources (e.g. standard search, ...",Work,NaN,Ukraine
24901,Online Courses or Certification (includes all ...,Personal Project,3.0,India
37353,NaN,Personal Project,20.0,Ukraine
...,...,...,...,...
484,Online Courses or Certification (includes all ...,Personal Project,5000.0,Zimbabwe
4062,Books / Physical media;AI CodeGen tools or AI-...,Work,6.0,Zimbabwe
13949,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe
41124,NaN,NaN,NaN,Zimbabwe
41192,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe

In [139]:
df_na.dropna(axis= 'index', how= 'any', subset= ['LearnCode', 'ToolCountWork'], inplace=True)

In [140]:
df_na.tail(20)

,LearnCode,TechEndorseIntro,ToolCountWork,Country
ResponseId,,,,
32228,Videos (not associated with specific online co...,Work,1.0,Viet Nam
32333,Online Courses or Certification (includes all ...,Personal Project,2.0,Viet Nam
35677,Online Courses or Certification (includes all ...,Personal Project,4.0,Viet Nam
35715,Online Courses or Certification (includes all ...,Personal Project,10.0,Viet Nam
35859,Online Courses or Certification (includes all ...,Work,11.0,Viet Nam
36295,Online Courses or Certification (includes all ...,Work,20.0,Viet Nam
37853,Online Courses or Certification (includes all ...,School,3.0,Viet Nam
40383,Stack Overflow or Stack Exchange;AI CodeGen to...,Work,25.0,Viet Nam
41506,Stack Overflow or Stack Exchange;Technical doc...,Work,5.0,Viet Nam
42909,"Other online resources (e.g. standard search, ...",Work,2.0,Viet Nam
43806,Online Courses or Certification (includes all ...,Work,6.0,Viet Nam
44656,Online Courses or Certification (includes all ...,School,7.0,Viet Nam
46126,"Other online resources (e.g. standard search, ...",Personal Project,2.0,Viet Nam
47602,Colleague or on-the-job training,Work,100.0,Viet Nam
47615,Online Courses or Certification (includes all ...,Personal Project,2.0,Viet Nam
37309,Videos (not associated with specific online co...,Work,4.0,Zambia
484,Online Courses or Certification (includes all ...,Personal Project,5000.0,Zimbabwe
4062,Books / Physical media;AI CodeGen tools or AI-...,Work,6.0,Zimbabwe
13949,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe
41192,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe

In [141]:
df_na['Country'].unique

<bound method Series.unique of ResponseId
24901                       India
30729                      Brazil
48024                   Australia
28059    United States of America
34976    United States of America
                   ...
37309                      Zambia
484                      Zimbabwe
4062                     Zimbabwe
13949                    Zimbabwe
41192                    Zimbabwe
Name: Country, Length: 18742, dtype: str>

In [142]:
df_na.isna()

            LearnCode  TechEndorseIntro  ToolCountWork  Country
ResponseId
24901           False             False          False    False
30729           False             False          False    False
48024           False             False          False    False
28059           False             False          False    False
34976           False             False          False    False
...               ...               ...            ...      ...
37309           False             False          False    False
484             False             False          False    False
4062            False             False          False    False
13949           False             False          False    False
41192           False             False          False    False

[18742 rows x 4 columns]

In [143]:
df_nan = df[['LearnCode', 'TechEndorseIntro', 'ToolCountWork', 'Country']].copy()

In [144]:
df_nan.fillna(0)

,LearnCode,TechEndorseIntro,ToolCountWork,Country
ResponseId,,,,
28701,0,Work,10.0,Ukraine
45972,Colleague or on-the-job training,Work,0.0,Netherlands
48429,"Other online resources (e.g. standard search, ...",Work,0.0,Ukraine
24901,Online Courses or Certification (includes all ...,Personal Project,3.0,India
37353,0,Personal Project,20.0,Ukraine
...,...,...,...,...
484,Online Courses or Certification (includes all ...,Personal Project,5000.0,Zimbabwe
4062,Books / Physical media;AI CodeGen tools or AI-...,Work,6.0,Zimbabwe
13949,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe
41124,0,0,0.0,Zimbabwe
41192,Online Courses or Certification (includes all ...,Personal Project,3.0,Zimbabwe

In [145]:
df_nan.dtypes

LearnCode               str
TechEndorseIntro        str
ToolCountWork       float64
Country                 str
dtype: object

In [146]:
df_nan['ToolCountWork'].agg(['mean', 'median'])

mean      15.149578
median     6.000000
Name: ToolCountWork, dtype: float64

In [147]:
nig_filt = df['Country'] == 'Nigeria'

In [148]:
df[nig_filt].head(2)

,MainBranch,Age,EdLevel,Employment,EmploymentAddl,WorkExp,LearnCodeChoose,LearnCode,LearnCodeAI,AILearnHow,YearsCode,DevType,OrgSize,ICorPM,RemoteWork,PurchaseInfluence,TechEndorseIntro,TechEndorse_1,TechEndorse_2,TechEndorse_3,TechEndorse_4,TechEndorse_5,TechEndorse_6,TechEndorse_7,TechEndorse_8,TechEndorse_9,TechEndorse_13,TechEndorse_13_TEXT,TechOppose_1,TechOppose_2,TechOppose_3,TechOppose_5,TechOppose_7,TechOppose_9,TechOppose_11,TechOppose_13,TechOppose_16,TechOppose_15,TechOppose_15_TEXT,Industry,JobSatPoints_1,JobSatPoints_2,JobSatPoints_3,JobSatPoints_4,JobSatPoints_5,JobSatPoints_6,JobSatPoints_7,JobSatPoints_8,JobSatPoints_9,JobSatPoints_10,JobSatPoints_11,JobSatPoints_13,JobSatPoints_14,JobSatPoints_15,JobSatPoints_16,JobSatPoints_15_TEXT,AIThreat,NewRole,ToolCountWork,ToolCountPersonal,Country,Currency,CompTotal,LanguageChoice,LanguageHaveWorkedWith,LanguageWantToWorkWith,LanguageAdmired,LanguagesHaveEntry,LanguagesWantEntry,DatabaseChoice,DatabaseHaveWorkedWith,DatabaseWantToWorkWith,DatabaseAdmired,DatabaseHaveEntry,DatabaseWantEntry,...,SOTagsHaveEntry,SOTagsWant Entry,OpSysPersonal use,OpSysProfessional use,OfficeStackAsyncHaveWorkedWith,OfficeStackAsyncWantToWorkWith,OfficeStackAsyncAdmired,OfficeStackHaveEntry,OfficeStackWantEntry,CommPlatformHaveWorkedWith,CommPlatformWantToWorkWith,CommPlatformAdmired,CommPlatformHaveEntr,CommPlatformWantEntr,AIModelsChoice,AIModelsHaveWorkedWith,AIModelsWantToWorkWith,AIModelsAdmired,AIModelsHaveEntry,AIModelsWantEntry,SOAccount,SOVisitFreq,SODuration,SOPartFreq,SO_Dev_Content,SO_Actions_1,SO_Actions_16,SO_Actions_3,SO_Actions_4,SO_Actions_5,SO_Actions_6,SO_Actions_9,SO_Actions_7,SO_Actions_10,SO_Actions_15,SO_Actions_15_TEXT,SOComm,SOFriction,AISelect,AISent,AIAcc,AIComplex,AIToolCurrently partially AI,AIToolDon't plan to use AI for this task,AIToolPlan to partially use AI,AIToolPlan to mostly use AI,AIToolCurrently mostly AI,AIFrustration,AIExplain,AIAgents,AIAgentChange,AIAgent_Uses,AgentUsesGeneral,AIAgentImpactSomewhat agree,AIAgentImpactNeutral,AIAgentImpactSomewhat disagree,AIAgentImpactStrongly agree,AIAgentImpactStrongly disagree,AIAgentChallengesNeutral,AIAgentChallengesSomewhat disagree,AIAgentChallengesStrongly agree,AIAgentChallengesSomewhat agree,AIAgentChallengesStrongly disagree,AIAgentKnowledge,AIAgentKnowWrite,AIAgentOrchestration,AIAgentOrchWrite,AIAgentObserveSecure,AIAgentObsWrite,AIAgentExternal,AIAgentExtWrite,AIHuman,AIOpen,SalaryUSD,JobSat
ResponseId,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
19537,I am a developer by profession,25-34 years old,"Professional degree (JD, MD, Ph.D, Ed.D, etc.)","Independent contractor, freelancer, or self-em...","Caring for dependents (children, elderly, etc.)",20.0,"No, I am not new to coding and did not learn n...",NaN,"Yes, I learned how to use AI-enabled tools req...",Other (please specify):,5.0,"Founder, technology or otherwise",NaN,NaN,NaN,"Yes, I endorsed a tool that was open-source an...",Personal Project,5.0,9.0,2.0,1.0,7.0,4.0,8.0,3.0,6.0,10.0,NaN,2.0,8.0,3.0,7.0,1.0,6.0,4.0,5.0,9.0,10.0,NaN,Energy,1.0,8.0,3.0,12.0,9.0,6.0,10.0,13.0,7.0,4.0,5.0,11.0,14.0,15.0,2.0,NaN,No,I have transitioned into a new career and/or i...,10.0,10.0,Nigeria,NGN\tNigerian naira,9.000000e+09,Yes,Ada;Assembly;Bash/Shell (all shells);C;C#;C++;...,Ada;Delphi;Elixir;Erlang;F#;Fortran;GDScript;G...,Ada;GDScript;Kotlin;Lisp;Lua;MATLAB;MicroPytho...,2023/2024,Yes,Yes,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;D...,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;D...,BigQuery;Cassandra;Cloud Firestore;Cosmos DB;D...,Yes but few,Yes but few,...,Yes approximately 2 just learning about Gemini,All google AI,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Windows;MacOS;Ubuntu;Android;Windows Subsystem...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Airtable;Asana;Azure Devops;Clickup;Coda;Confl...,Yes about 10,Yes for different Business Network Marketing,Stack Overflow;Stack Exchange;Discord;Reddit;D...,Stack Overflow;Stack Exchange;Discord;Reddit;D...,Stack Overflow;Stack Exchange;Discord;Reddit;D...,10,Yes but don't have the access,True,Alibaba Cloud Qwen models;Amazon Titan models;...,Alibaba Cloud Qwen models;Amazon Titan models;...,Alibaba Cloud Qwen models;Amazon Titan models;...,4,Yes,Yes,A few times per month or weekly,Less than one year,I have never participated in Q&A on Stack Over...,Chat (people);Message Boards;Long-form article...,5.0,1.0,4.0,7.0,9.0,2.0,3.0,6.0,8.0,10.0,NaN,"Yes, definitely",More than half the time,"Yes, I use AI tools daily",Favorable,Highly trust,Very well at handling complex tasks,NaN,Debugging or fixing code,Learning about a codebase;Project planning;Wri...,NaN,NaN,I don’t use AI tools regularly;Other (write in):,Yes,"No, I use AI exclusively in copilot/autocomple...","No, but my development work has significantly ...",Software engineering;Business process automati...,Multi-platform search enablement;Language proc...,NaN,AI agents have reduced the time spent on speci...,AI agents have increased my productivity.;AI a...,NaN,NaN,It takes significant time and effort to learn ...,NaN,The cost of using certain AI agent platforms i...,I am concerned about the accuracy of the infor...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I want to compare different solutions;Oth...,Me as an Artificial Intelligence Oracle,5810837.0,10.0
22093,I am a developer by profession,25-34 years old,"Bachelor’s degree (B.A., B.S., B.Eng., etc.)","Independent contractor, freelancer, or self-em...",Engaged in paid work (20-29 hours per week),10.0,"Yes, I am not new to coding but am learning ne...",Online Courses or Certification (includes all ...,"Yes, I learned how to use AI-enabled tools req...","Other online resources (e.g. standard search, ...",12.0,"Developer, mobile","10,000 or more employees",Individual contributor,Remote,No,Personal Project,5.0,1.0,3.0,9.0,7.0,8.0,6.0,4.0,2.0,10.0,NaN,8.0,3.0,7.0,1.0,2.0,6.0,4.0,5.0,9.0,10.0,NaN,Fintech,8.0,7.0,1.0,14.0,13.0,12.0,11.0,2.0,5.0,9.0,4.0,6.0,10.0,15.0,3.0,NaN,No,I have somewhat considered changing my career ...,3.0,6.0,Nigeria,USD United States dollar,6.000000e+04,Yes,Java;Kotlin;Ruby;SQL;Swift,Java;Kotlin;SQL;Swift,Java;Kotlin;SQL;Swift,NaN,NaN,Yes,PostgreSQL;SQLite,Cloud Firestore;MySQL;PostgreSQL;Redis;SQLite,PostgreSQL;SQLite,NaN,NaN,...,NaN,NaN,MacOS,MacOS,Confluence;GitHub;Jira;Notion,Confluence;GitHub;Jira;Linear,Confluence;GitHub;Jira,NaN,NaN,"Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...","Stack Overflow;GitHub (public projects, not pr...",NaN,NaN,True,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,Anthropic: Claude Sonnet;Gemini (Pro Reasoning...,NaN,NaN,Yes,Daily or almost daily,Between 10 and 15 years,A few times per month or weekly,Chat (bot/AI),4.0,2.0,8.0,3.0,7.0,1.0,6.0,5.0,9.0,10.0,NaN,"No, not really",About half of the time,"Yes, I use AI tools daily",Very favorable,Neither trust nor distrust,"Good, but not great at handling complex tasks",Learning about a codebase;Writing code;Debuggi...,Deployment and monitoring;Predictive analytics,Project planning;Committing and reviewing code,Testing code;Learning new concepts or technolo...,Documenting code;Search for answers;Creating o...,"AI solutions that are almost right, but not qu...","No, I highly discourage it","No, I use AI exclusively in copilot/autocomple...","Yes, to a great extent",Software engineering,NaN,AI agents have helped me automate repetitive t...,AI agents have increased my productivity.;AI a...,AI agents have improved collaboration within m...,NaN,NaN,The cost of using certain AI agent platforms i...,NaN,I am concerned about the accuracy of the infor...,Integrating AI agents with my existing tools a...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,When I don’t trust AI’s answers;When I want to...,"Software Architecture, Security, Enforcing Bes...",60000.0,10.0

In [149]:
nig_filt.to_csv('data/modified.csv')

In [150]:
nig_filt.to_excel('data/modified.xlsx')

In [151]:
test = pd.read_csv('data/modified.csv')

In [152]:
test['Country'].value_counts()

Country
False    31525
True       146
Name: count, dtype: int64